### ISSUE TITLE
支付宝小程序在ios打开白屏,android系统没有问题,用demo也是一样

### ISSUE THREAD

**Issue by zhj296409022** [kaola-fed/megalo#104]
打开就报错:
"[WORKER] onerror ["TypeError: c.createElement is not a function.(In 'c.createElement("script")','c.createElement' is undefined)","",0,0,{}]"

**Comment by zhj296409022** [comment]
已向支付宝客服反馈，解决方法见：
#62

**Comment by xiexieni1992** [comment]
megalo版本依旧还在报这个错误。。[WORKER] onerror ["c.createElement is not a function. (In 'c.createElement(\"script\")', 'c.createElement' is undefined)","https://2018071660710198.hybrid.alipay-eco.com/index.worker.js",1,341522,{"line":1,"column":341522,"sourceURL":"https://2018071660710198.hybrid.alipay-eco.com/index.worker.js"}]
