### ISSUE TITLE
编译生成的文件太大了，写了个测试页面，编译后都接近1M

### ISSUE THREAD

**Issue by q310550690** [kaola-fed/megalo#106]

**Comment by elcarim5efil** [comment]
`megalo@0.7.0`，`@megalo/template-compiler@0.7.0` 对生成的代码有了优化，可以试试[changelog](http://megalojs.org/#/changelog/CHANGELOG?id=_070-20190101)。

另外确认一下是否提取了 common chunk，demo 里没有做这个配置，后面我们会补上。

**Comment by q310550690** [comment]
好的，谢谢
