### ISSUE TITLE
关于推广，人多了才能发展起来

### ISSUE THREAD

**Issue by luooyii** [kaola-fed/megalo#107]
百度上搜不到megalo的官网，为什么不弄个官方论坛。而且方向和uniapp很像，如果可以适配uniapp，使用人数一下能多很多

**Comment by Airkro** [comment]
从关系上讲是 uniapp 对 megalo 进行适配吧。而且 uniapp 的适配 dcloud 方面已经在内测了。

交流的话请进交流群
