### ISSUE TITLE
配置了编译es6，为什么报错？

### ISSUE THREAD

**Issue by flexmodule** [kaola-fed/megalo#110]
E:\github\my-megalo-pro\build\createBaseConfig.js:46
      ...pagesEntry(appMainFile)
      ^^^

SyntaxError: Unexpected token ...

{
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "safari >= 7"]
      },
      "debug": false
    }]
    , "stage-0"
  ],
  "plugins": [
    ["transform-runtime", {
      "helpers": false,
      "polyfill": false,
      "regenerator": true   
    }]
  ]
}

**Comment by fengzilong** [comment]
nodejs 版本太低了，请升级到 8.6.0 及以上版本
