### ISSUE TITLE
是否有考虑编译到HyperApp开发平台APICloud？

### ISSUE THREAD

**Issue by wxs77577** [kaola-fed/megalo#111]
apicloud的今日头条APP项目源码：
https://github.com/apicloudcom/APICloud-App-Templates/tree/master/toutiao/widget

apicloud开发app就是每个页面一个html，里面用原始的html、css和js来写。请问是否有计划支持？

如果没有，是否能麻烦给点提示？

**Comment by elcarim5efil** [comment]
这个项目都是 h5 端的吧？而且用的是原生 js 开发，跟 Vue 的开发模式差异应该比较大。
