### ISSUE TITLE
很多第三方组件key关键字冲突

### ISSUE THREAD

**Issue by archimate** [kaola-fed/megalo#112]
![image](https://user-images.githubusercontent.com/8114237/50536039-2fb10200-0b8b-11e9-8509-36aecaff72f0.png)h很多第三方组件要求【key】作为属性来使用，但是框架也使用【key】，导致页面直接报错，希望处理这个关键字

**Comment by elcarim5efil** [comment]
试一下 mp:key 这种写法， #71

**Comment by elcarim5efil** [comment]
已更新到文档，[使用原生自定义组件](http://megalojs.org/#/senarios/custom-component)
