### ISSUE TITLE
textarea  双向绑定失败

### ISSUE THREAD

**Issue by dxr199212300** [kaola-fed/megalo#113]
<textarea class="textarea" v-model="theData"></textarea>

WeChat developer tool testing is OK 

 phone test value is null

**Comment by elcarim5efil** [comment]
textarea 在微信上应该是以 native 组件的形式做的，目前发现 data-set 字段无法进行动态绑定（怀疑是一个 bug），所以在事件触发以后无法找到对应的 hanlder。目前我们是用原生自定义组件的方法绕开。

定义一个自定义组件 textarea，通过这个自定义组件将 dataSet 返回出去，让框架能够进行定位。

index.wxml

```html
<textarea
  placeholder="{{placeholder}}"
  placeholder-style="{{placeholderStyle}}"
  placeholder-class="{{placeholderClass}}"
  disabled="{{disabled}}"
  auto-focus="{{autoFocus}}"
  focus="{{focue}}"
  auto-height="{{autoHeight}}"
  fixed="{{fixed}}"
  cursor-spacing="{{cursorSpacing}}"
  cursor="{{cursor}}"
  show-confirm-bar="{{showConfirmBar}}"
  selection-start="{{selectionStart}}"
  selection-end="{{selectionEnd}}"
  adjust-position="{{adjustPosition}}"
  maxlength="{{maxlength}}"
  value="{{value}}"

  bindinput="proxy"
  bindblur="proxy"
  bindfocus="proxy"
  bindblur="proxy"
  bindlinechange="proxy"
>
</textarea>
```

index.js

```javascript
Component({
    properties: {
        placeholder: { type: String, value: '' },
        placeholderStyle: { type: String, value: '' },
        placeholderClass: { type: String, value: '' },
        disabled: { type: Boolean, value: false },
        autoFocus: { type: Boolean, value: false },
        focus: { type: Boolean, value: false },
        autoHeight: { type: Boolean, value: false },
        fixed: { type: Boolean, value: false },
        cursorSpacing: { type: Number | String, value: 0 },
        cursor: { type: Number, value: 0 },
        showConfirmBar: { type: Boolean, value: true },
        selectionStart: { type: Number, value: -1 },
        selectionEnd: { type: Number, value: -1 },
        adjustPosition: { type: Boolean, value: true },
        maxlength: { type: Number, value: 140 },
        value: { type: String, value: '' }
    },
    methods: {
        proxy(e) {
            this.triggerEvent(e.type, e.detail);
        }
    }
});
```

index.wxss

```css
textarea{
	width:inherit;
	height:inherit;
	display:inherit;
	position:inherit;
}
```

**Comment by elcarim5efil** [comment]
已更新内容到文档：[textarea 上使用 v-model](http://megalojs.org/#/senarios/textarea)

**Comment by nicolesite** [comment]
@elcarim5efil 使用了报错 “Maximum call stack size exceeded;onAppRoute”

**Comment by elcarim5efil** [comment]
参考一下这个 [demo](https://github.com/kaola-fed/megalo-demo/blob/master/src/pages/v-model/Model.vue)。

**Comment by sxx97** [comment]
@elcarim5efil  使用后一直提示 `Component is not found in path "native/wechat/textarea/index"` ,这个会和webpack的配置有关吗

**Comment by elcarim5efil** [comment]
指的是 demo 吗？demo 里面 [copy plugin](https://github.com/kaola-fed/megalo-demo/blob/master/build/createBaseConfig.js#L151) 会将平台对应的自定义组件拷贝到 dist 目录，同时吧 wechat 这一级路径去掉，变成 `dist/native/textarea/index`。主要目的是让不同平台下加载路径保持一致。

**Comment by sxx97** [comment]
![image](https://user-images.githubusercontent.com/40782717/50885768-9bb42580-1429-11e9-9259-54016f8aa623.png)

**Comment by sxx97** [comment]
@elcarim5efil 这是我这报的错,然后我看了demo的例子改的,不知道哪里出的错
![image](https://user-images.githubusercontent.com/40782717/50885826-c69e7980-1429-11e9-9b00-b6a485d43714.png)

**Comment by sxx97** [comment]
是不是去掉wechat就好了

**Comment by elcarim5efil** [comment]
先检查一下 dist 下 textarea 是否存在。usingComponents 的路径要跟 dist 目录下文件路径对应上。

**Comment by sxx97** [comment]
@elcarim5efil 好了,在入口的js文件中去掉了 wechat 现在正常了。谢谢回复
