### ISSUE TITLE
百度小程序运行与微信小程序运行的不协调

### ISSUE THREAD

**Issue by Raingor** [kaola-fed/megalo#118]
问题是这样的
      **我在百度小程序 运行没问题
      微信小程序上会报错报了个 Page未定义的请问怎么处理呢？**
还有一个问题是
     第三方组件的问题，微信的第三方组件的路径是
    `
    "usingComponents": {
      "i-button": "../../iview-weapp/dist/button/index"
    },`
    官方的文档是 不用 "../../" 这个前缀的
   两个方式都试过  可是百度小程序引入第三方都没反应

**Comment by elcarim5efil** [comment]
1. 所使用的依赖版本是多少？
2. iview-weapp 支持百度小程序吗？

**Comment by Raingor** [comment]
> * 所使用的依赖版本是多少？
vue和vue-template-compiler 的版本是2.5.21
> * iview-weapp 支持百度小程序吗？
 iview 的确不支持百度小程序

**Comment by Raingor** [comment]
> 请提供 meglao、@megalo/template-compiler、@megalo/target 的版本

- megalo 0.3.1

- target 0.5.5

- template-compiler 0.6.3 和 0.7.0

这样纸

**Comment by elcarim5efil** [comment]
megalo@0.7.0
@megalo/target@0.7.0

更新一下再试试。另外用了 @megalo/entry  吗？

**Comment by Raingor** [comment]
> megalo@0.7.0
> @megalo/target@0.7.0
> 
> 更新一下再试试。另外用了 @megalo/entry 吗？

好的 我先试试，  用了 版本是 0.1.1的

**Comment by Raingor** [comment]
> megalo@0.7.0
> @megalo/target@0.7.0
> 
> 更新一下再试试。另外用了 @megalo/entry 吗？

**Comment by Raingor** [comment]
已经OK了 就是megalo的 版本问题
