### ISSUE TITLE
[feat] setData 时间间隔可配置

### ISSUE THREAD

**Issue by elcarim5efil** [kaola-fed/megalo#124]
以页面为维度配置 setData 时间间隔，给业务代码调优使用。目前 setData 节流写死 50ms，在 js 操作动画时会严重掉帧。节流时间间隔可配置，粒度为页面。

除了时间可配置以外，考虑指定的组件、属性、标签的数据更新频率可配置。

**Comment by xiaoxintang** [comment]
请问这个是不是造成我页面（10毫秒级别）抢购倒计时卡顿（大概1s动一次）的问题根源所在

**Comment by elcarim5efil** [comment]
你的问题应该不是这个原因导致。倒计时页面是不是有大量数据在视图中展示？当页面中有大量数据需要展示时，渲染更新一条数据会有一定的性能问题。有两个可以尝试的解决方案：

1. 倒计时的毫秒部分用 css 动画做。
2. 倒计时组件用一个自定义组件实现，内部做倒计时逻辑。
