### ISSUE TITLE
百度小程序web化出错

### ISSUE THREAD

**Issue by torns** [kaola-fed/megalo#127]
使用百度小程序开发工具 web化后,浏览器访问出错
![1121](https://user-images.githubusercontent.com/23144884/51224923-3315fd00-1983-11e9-9190-9e890369a058.png)

**Comment by elcarim5efil** [comment]
web 化指的是？

**Comment by torns** [comment]
![12](https://user-images.githubusercontent.com/23144884/51229311-e0464080-1996-11e9-86f3-2506d3b053ae.png)
百度小程序要求必须支持web预览才能做seo优化

**Comment by rqingfu** [comment]
> 我们暂时没有可以测试的工程，按照你提供的报错信息，尝试进行修改，如果可以的话，可以帮忙用预览版@megalo/0.7.4-2，测试一下吗？

我换了试了一下，没有报了～

**Comment by elcarim5efil** [comment]
@rqingfu 谢谢帮忙。

定位原因是 Vue 的 `[core/util/env](https://github.com/kaola-fed/megalo/blob/master/src/core/util/env.js#L10)` 导致。但我们的原本设想是不修改 core 的代码，方便日后跟着 Vue 的版本升级。

@bigmeow 提供了思路通过 babel 插件把这一类会引发报错的代码在编译时干掉。

**Comment by rqingfu** [comment]
> @rqingfu 谢谢帮忙。
> 
> 定位原因是 Vue 的 `[core/util/env](https://github.com/kaola-fed/megalo/blob/master/src/core/util/env.js#L10)` 导致。但我们的原本设想是不修改 core 的代码，方便日后跟着 Vue 的版本升级。
> 
> @bigmeow 提供了思路通过 babel 插件把这一类会引发报错的代码在编译时干掉。

这个问题百度已经做了修复，刚测试了一下，没报错了
