### ISSUE TITLE
代码组织与可读性问题

### ISSUE THREAD

**Issue by gaoupon** [kaola-fed/megalo#13]
提个小建议，感觉源码阅读起来还是很吃力的，大部分都是 Vue 的源码，不知道 megalo 的代码具体分布在哪里， 开源的目的应该就是要让大家发现问题找到问题， 这样好像不太好提 pr😂

**Comment by elcarim5efil** [comment]
megalo 的源码全在 `src/platforms/mp` 目录下，`src/core` 部分没有修改。有些模块 Vue 原本不提供修改接口，我们将部分 core 的源码拷贝到  `src/platforms/mp` 目录下，例如 path 的逻辑是拷贝到 `src/platforms/mp/runtime/vdom/patch.js` 再作修改，这类代码相对较少。
