### ISSUE TITLE
Megalo.request 函数不存在

### ISSUE THREAD

**Issue by sd4888108** [kaola-fed/megalo#133]
在使用Megalo.api 的时候 在createBaseConfig.js配置了 全局变量
  new webpack.ProvidePlugin({
    'Megalo': [path.resolve(`./node_modules/@megalo/api/platforms/${platform}`), 'default']
  })

结果只有 微信小程序、百度小程序 可以正常访问 api，支付宝的提示Megalo.request 函数不存在。
警告信息：支付宝小程序暂不支持 my.default
错误信息：Megalo.request is not a function
请问下是否有 api的Demo

**Comment by zhuping** [comment]
配置改成下面的试试，注意 api 的目录地址

```js
new webpack.ProvidePlugin({
  'Megalo': [_.resolve(`./node_modules/@megalo/api/platforms/${platform}`), 'default']
}),
```

**Comment by sd4888108** [comment]
OK 已经解决，可能是因为修改了 Megalo.api 的代码了， 最后从新安装了一次问题就好了
