### ISSUE TITLE
打包时,静态资源文件不会复制到dist目录,需要手动复制过去

### ISSUE THREAD

**Issue by yuxuelian** [kaola-fed/megalo#134]

**Comment by Airkro** [comment]
megalo-demo 目前默认会复制src/native目录。
因为每个人的需要不同，需要自定义的话请自行配置CopyWebpackPlugin实现。

**Comment by elcarim5efil** [comment]
是的，可以通过自行配置 copyWebpackPlugin 或者通过 url-loader 去做。
