### ISSUE TITLE
使用keyframe报错

### ISSUE THREAD

**Issue by WhatMakesPeopleLazy** [kaola-fed/megalo#135]
使用的scss,
初始化后，在hello.vue下添加个@keyframe样式报错

`<style lang="scss" scoped>
.app {
  padding-top: 100px;
  .img {
    display: block;
    height: 120px;
    width: 138px;
    margin: 20px auto;
    animation: scales infinite alternate 500ms;
  }
  .txt {
    color: #567567;
    font-size: 13px;
    text-align: center;
  }
}

@keyframes scales {
  0% {
    transform: scale(0.8);
  }

  50% {
    transform: scale(1);
  }

  100% {
    transform: scale(1.3);
  }
}
</style>`

报错信息：
`ERROR in ./src/pages/hello.vue?vue&type=style&index=0&id=4bcda7fe&lang=scss&scoped=true& (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader!./node_modules/@megalo/target/lib/frameworks/vue/loader/style.js!./node_modules/@megalo/px2rpx-loader??ref--3-2!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib??vue-loader-options!./src/pages/hello.vue?vue&type=style&index=0&id=4bcda7fe&lang=scss&scoped=true&)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/@megalo/target/lib/frameworks/vue/loader/style.js):
TypeError: Cannot read property 'selector' of undefined`

版本：
`"dependencies": {
    "@megalo/vhtml-plugin": "^0.1.2",
    "megalo": "^0.7.0",
    "octoparse": "^0.3.2"
  }`

**Comment by WhatMakesPeopleLazy** [comment]
我把@keyframes 改成@-webkit-keyframes可以了,

**Comment by elcarim5efil** [comment]
@megalo/target 用的是哪个版本? 可能和这个问题类似：kaola-fed/megalo-aot#72
