### ISSUE TITLE
突然不能打包了

### ISSUE THREAD

**Issue by JokerLoLgrey** [kaola-fed/megalo#136]
![image](https://user-images.githubusercontent.com/33446705/51512447-fba2c700-1e40-11e9-8805-977cd65676d9.png)
情况如下：在调用webview的页面加了样式，添加了onShow和created生命周期函数，但是没有触发dev刷新，就重新打包，然后就发现不能打包了，而且也不报是什么原因不能打包
ps： 由于是移植mpvue的代码，经常复制粘贴，然后不能触发自刷新，就经常重新dev，不知是否这个原因造成的

pps：刚刚重新下载模板，重新构建还是不能

这是依赖
![image](https://user-images.githubusercontent.com/33446705/51515619-63f8a500-1e4f-11e9-942b-fc51b00c64be.png)

**Comment by JokerLoLgrey** [comment]
@elcarim5efil

**Comment by elcarim5efil** [comment]
是通过更新到最新版解决的吗？

**Comment by JokerLoLgrey** [comment]
> 是通过更新到最新版解决的吗？

是我自己的js问题，提个建议，希望能整合下webpack，检测一下js错误，比如async await之类的，然后打印出来，而不是直接跳出打包
