### ISSUE TITLE
定时器

### ISSUE THREAD

**Issue by xiaoxintang** [kaola-fed/megalo#137]
- 代码与复现步骤
页面需要有一个抢购倒计时显示（10毫秒级别），
- 问题现象
倒计时卡顿，约1S跑一次，（检查过多次，代码没有问题，现在部分页面已经改为原生（写成原生没问题））

![image](https://user-images.githubusercontent.com/24927686/51522644-d2942d80-1e64-11e9-9f6b-77efb402aeab.png)

**Comment by elcarim5efil** [comment]
倒计时页面是不是有大量数据在视图中展示？当页面中视图中已有大量数据时，渲染更新一条数据会有一定的性能问题。有两个可以尝试的解决方案：

1. 倒计时的毫秒部分用 css 动画做。
2. 倒计时组件用一个自定义组件实现，内部做倒计时逻辑。

**Comment by bigmeow** [comment]
建议倒计时部分抽象出来，用小程序原生组件写，用原生的setData来绕过；另外就算数据不大，megalo也做了函数节流

**Comment by xiaoxintang** [comment]
![image](https://user-images.githubusercontent.com/24927686/51579633-aaf0a400-1efc-11e9-9d8e-93438a260962.png)

1、当前页面是tab页面，当前页面没有大量数据（只有能看到的这些），测试的时候是添加新的编译模式，直接打开这一页，没有进行tab跳转（我想跟其他页面的数据量应该没有什么关系）
2、切换实现过以下方式(都不行)：
    a、 goods封装为组件方式，每个goods内部有自己的定时器
    b、goods只是显示，父组件统一跑一个定时器修改子组件props
3、页面有websocket
4、现在已经原生化(半原生半框架，websocket,userInfo各种信息同步等问题，目前靠globalData解决)

**Comment by xiaoxintang** [comment]
> 建议倒计时部分抽象出来，用小程序原生组件写，用原生的setData来绕过；另外就算数据不大，megalo也做了函数节流

对哦，我怎么没想到将倒计时抽出为原生组件，我只想到了整个页面原生化，哈哈

**Comment by bigmeow** [comment]
页面原生化，混到一起，不方便管理，很不推荐
