### ISSUE TITLE
使用新的 cli 创建项目，如何引入环境变量？

### ISSUE THREAD

**Issue by Kidwind** [kaola-fed/megalo#139]
我使用 megalo-env-plugin ，按照说明进行配置，但更改 package.json 中的
dev:wechat 就无法运行
原配置：
"dev:wechat": "webpack --config ./build/webpack.config.wechat.js -w"
变更后配置：
"dev:wechat": "node ./build/megalo-cli.js --mode development --platform wechat"

感觉是因为 megalo 升级后配置变更的原因。

**Comment by bigmeow** [comment]
你用的应该是很老版本的了，没有`./build/megalo-cli.js`这个文件 ，变更配置后你应该改成这个命令：
`"dev:wechat": "webpack --config ./build/webpack.config.wechat.js --mode development --platform wechat"`
 @Kidwind  配置有问题优先在群里提问， 可以@ 我

**Comment by Kidwind** [comment]
@bigmeow 我的megalo-cli和megalo版本都是比较新的哦，感觉是不是megalo-env-plugin这个只适配了老版本的megao呢，请问你在群里的ID是多少？

**Comment by bigmeow** [comment]
我头像和github头像一样 @bigmeow
