### ISSUE TITLE
使用原生组件时如果使用了原生组件的 slot，npm run dev:wechat 会报错。

### ISSUE THREAD

**Issue by Kidwind** [kaola-fed/megalo#140]
请提供如下信息：
- 代码与复现步骤
1、引入原生组件，例如使用 iView 的 i-cell 组件。
2、在页面中使用组件：
`<i-cell>
          内容1
          <a href="../seller-join/main" slot="footer">
              内容2
          </a>
      </i-cell>`
3、npm run dev:wechat 报错。
- 问题现象
npm run dev:wechat 报错。
- 版本。
"@megalo/target": "^0.5.5"
"megalo": "^0.7.0"
"@megalo/template-compiler": "^0.7.0"
- 操作系统信息
Windows7

附件里包含测试代码
[megalo-test.zip](https://github.com/kaola-fed/megalo/files/2794551/megalo-test.zip)

**Comment by elcarim5efil** [comment]
修复了，更新试试。
megalo@0.7.5
@megalo/template-compiler@0.7.5
