### ISSUE TITLE
slot 上有v-if vif 不生效

### ISSUE THREAD

**Issue by DestinyHunter** [kaola-fed/megalo#142]
rt
![image](https://user-images.githubusercontent.com/20897838/51727183-ccd95a80-20a5-11e9-92f2-80bf0476d383.png)
![image](https://user-images.githubusercontent.com/20897838/51727239-09a55180-20a6-11e9-965c-9230471b5fc3.png)
![image](https://user-images.githubusercontent.com/20897838/51727241-0ca04200-20a6-11e9-9609-20619ddb172a.png)

**Comment by elcarim5efil** [comment]
#34
