### ISSUE TITLE
升级 0.7.5 后又有新问题，a 链接的 :href="'pages/help'" 开始报错了。

### ISSUE THREAD

**Issue by Kidwind** [kaola-fed/megalo#145]
[Issues 140](https://github.com/kaola-fed/megalo/issues/140)修复后，新的问题产生了，a 链接的 :href="'pages/help'" 开始报错了。附件中有代码。
[megalo-test.zip](https://github.com/kaola-fed/megalo/files/2798473/megalo-test.zip)

**Comment by elcarim5efil** [comment]
如果是设置常量，可以不需要用绑定语法，不过这个问我们也修复一下。

**Comment by elcarim5efil** [comment]
已修复，`megalo@0.7.6`，`@megalo/template-compiler@0.7.6`。

**Comment by Kidwind** [comment]
嗯，我只是为了展示所以写成了常量，实际应用并不是常量的，我试试看，谢谢了！

**Comment by Kidwind** [comment]
测试已经解决了，谢谢！
