### ISSUE TITLE
小程序生命周期抛出异常会使整个页面的js停止工作

### ISSUE THREAD

**Issue by tvolitt** [kaola-fed/megalo#148]
![image](https://user-images.githubusercontent.com/18397319/51819126-3ce91a00-230c-11e9-9539-2e885c75b78e.png)
![image](https://user-images.githubusercontent.com/18397319/51819138-51c5ad80-230c-11e9-986b-b253719757e9.png)
小程序onLoad的异常，使得之后的js被终止
期望小程序生命周期的异常能被捕获，否则岂不是要每个生命周期函数里都要写try catch

**Comment by elcarim5efil** [comment]
好建议，异常捕获可以有的，Vue 本身也是这么做的，当时我们没考虑全。下一个版本加上。
