### ISSUE TITLE
默认安装，提示vue包不匹配。

### ISSUE THREAD

**Issue by fengzhiqiang012** [kaola-fed/megalo#158]
Vue packages version mismatch:

- vue@2.5.16
- vue-template-compiler@2.5.17

清除packge-lock.json 和 node_modules 也不行

**Comment by elcarim5efil** [comment]
试试把 vue 去掉，没有用到 vue 的

**Comment by fengzhiqiang012** [comment]
> 试试把vue去掉，没有用到vue的

并没什么用 ，很纳闷

**Comment by elcarim5efil** [comment]
可以提供 package.json 和 webpack 配置吗？

**Comment by fengzhiqiang012** [comment]
> 可以提供 package.json 和 webpack 配置吗？

解决了 我本地的问题 我本地全局上有个vue包的问题
