### ISSUE TITLE
最新版本process.env.PLATFORM这个变量怎么没有了

### ISSUE THREAD

**Issue by zhj296409022** [kaola-fed/megalo#162]
我现在如何在编译时区分PLATFORM

**Comment by bigmeow** [comment]
用的哪套模版，只有使用了https://github.com/megalojs/megalo-env-plugin 或者 https://github.com/megalojs/megalo-cli-service 才有

**Comment by zhj296409022** [comment]
@bigmeow 改了demo里的配置好了，原先用的默认的，没用这个模板
