### ISSUE TITLE
这个性能问题怎么破？

### ISSUE THREAD

**Issue by Kidwind** [kaola-fed/megalo#163]
- 问题现象：把之前的项目从mpvue移植到megalo，基本上都很顺利，但有一个业务场景下，发现随着数据量的增大，页面响应明显变慢，但这个问题在mpvue时是不存在的。
该业务是需要显示一个表格，表格显示一段时间内各个房间的使用情况，为了便于显示，我把非表格结构的数据转换成了便于表格显示的数据结构，具体代码请看附件中的 test3.vue 页面。当打开这个页面时，显示明显比其它页面慢了很多，我在页面上方加了一个计数操作，每点击按钮大概都要经过几秒钟才能在页面中反应出来。
- 版本。
"@megalo/target": "^0.5.5"
"megalo": "^0.7.0"
"@megalo/template-compiler": "^0.7.0"
- 操作系统信息
Windows7

[megalo-test.zip](https://github.com/kaola-fed/megalo/files/2863971/megalo-test.zip)

**Comment by elcarim5efil** [comment]
附件代码好像没有看到 test3.vue 文件？

**Comment by Kidwind** [comment]
@elcarim5efil 我下载下来看是有的啊，在 src/pages 目录下

**Comment by elcarim5efil** [comment]
建议拆分组件，我尝试把每一行拆分后，性能有所提升
![image](https://user-images.githubusercontent.com/8703947/52833156-8b712380-3116-11e9-9c18-2c74c0055500.png)

**Comment by Kidwind** [comment]
@elcarim5efil 好的，我回头试试看，还想问一下在框架底层有没有办法根治此类问题，毕竟这类场景还是比较普遍的。

**Comment by Kidwind** [comment]
@elcarim5efil 经测试，这样一改性能确实有所提升，先这么用着，但还是希望能够从底层上去解决此类问题，谢谢！

**Comment by Kidwind** [comment]
@elcarim5efil 这样弄只是会比以前稍好很多，但数据量再加大一些的话，还是会卡挺卡的，希望能够优化。

**Comment by elcarim5efil** [comment]
嗯，一直在探索优化方案。

**Comment by elcarim5efil** [comment]
先关闭，后续有问题再 open
