### ISSUE TITLE
在使用vue-awesome-swiper 或者 vue-amap时报错

### ISSUE THREAD

**Issue by y213140** [kaola-fed/megalo#168]

**Comment by y213140** [comment]
thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'Swiper' of undefined 
 TypeError: Cannot read property 'Swiper' of undefined

**Comment by elcarim5efil** [comment]
请提供可复现代码

**Comment by y213140** [comment]
import App from './App'
import Vue from 'vue'
import VHtmlPlugin from '@megalo/vhtml-plugin'
import Vueswiper from 'vue-awesome-swiper'
在这里引入时 开发者工具就直接报错了

**Comment by elcarim5efil** [comment]
vue-awesome-swiper 这个包引用了 [swiper](https://github.com/nolimits4web/swiper)，然而 swiper 是浏览器端的组件，无法在小程序中使用。[vue-amap](https://github.com/ElemeFE/vue-amap) 用的是高德地图，再微信小程序中能够使用吗？

如果要引入第三方的 Vue 组件，需要直接引用组件的 .vue 源码，megalo 构建时需要对这些组件重新编译生成模版，如果引用的是 js 文件就无法编译了。

**Comment by y213140** [comment]
？ 组件的.vue源码？  能否举个例子  十分感谢

**Comment by elcarim5efil** [comment]
类似 [megalo-ui](https://github.com/megalojs/megalo-ui)，直接引用 .vue 文件，而不是打包输出的 .js 文件。
