### ISSUE TITLE
新手请教

### ISSUE THREAD

**Issue by haharwj** [kaola-fed/megalo#171]
小弟是后端因为兴趣转过来的前端新手，请问：
1、怎么能够及时更新框架呢？是需要每次构建新的吗？以前的项目怎么更新？
2、megalo怎么跳转页面，api没有看到。

**Comment by bigmeow** [comment]
1. 使用 https://github.com/megalojs/megalo-cli-service 后，更新框架只需要改package.json的版本号即可
2.跳转页面和小程序官方文档的的一样
