### ISSUE TITLE
关于编译错误提示小问题

### ISSUE THREAD

**Issue by chang0022** [kaola-fed/megalo#172]
#### 问题原因：

初始化项目，同事之前一起开发，合并代码的时候 merge 某个 vue 文件的 script 出现错误。编译的时候如下图。
![image](https://user-images.githubusercontent.com/6067222/53317717-b4a86580-3907-11e9-8bd2-73b4609aa551.png)
编译错误了，但没有异常抛出。
`production`如下，就 Done 了
![image](https://user-images.githubusercontent.com/6067222/53318117-259c4d00-3909-11e9-810f-b7fce7afc727.png)

#### 开发环境：
`megalo-cli`
```
"@megalo/api": "^0.2.2",
"@megalo/vhtml-plugin": "^0.1.2",
"megalo": "^0.7.3",
```

**Comment by elcarim5efil** [comment]
可以提供可复现的代码吗？构建有异常不抛出确实有问题。

**Comment by chang0022** [comment]
> 可以提供可复现的代码吗？构建有异常不抛出确实有问题。

很简单，比如如图的低级错误。

**Comment by elcarim5efil** [comment]
![image](https://user-images.githubusercontent.com/8703947/53469073-89ed1700-3a97-11e9-85fb-294bdc8a5cb5.png)
应该是 cli 某些插件把异常吞了，直接启动 webpack 是正常的。 @zwwill

**Comment by chang0022** [comment]
> ![image](https://user-images.githubusercontent.com/8703947/53469073-89ed1700-3a97-11e9-85fb-294bdc8a5cb5.png)
> 应该是 cli 某些插件把异常吞了，直接启动 webpack 是正常的。 @zwwill
