### ISSUE TITLE
在不希望有转发的页面出现了转发功能

### ISSUE THREAD

**Issue by poi-mashiro** [kaola-fed/megalo#174]
- 代码与复现步骤
```vue
<template>
  <web-view :src="mpUrl"></web-view>
</template>

<script>
export default {
  data() {
    return {
      mpUrl: '',   // 一个安全域名的网页
    };
  },

  /**
   * 生命周期函数--监听页面加载
   */
  onLoad: function(options) {
    this.mpUrl = decodeURIComponent(options.mpUrl);
  },
};
</script>
```
- 问题现象
在没有提供 onShareAppMessage 的页面 点击顶上 ... 出现了 
![image](https://user-images.githubusercontent.com/29301772/53381918-559d2c00-39ad-11e9-8b30-a9a049f62f37.png)  
希望在没有提供 onShareAppMessage 的页面上  不出现转发功能  
查看了编译后的 js 文件，没有 onShareAppMessage 的 .vue 输出的结果中  没有 onShareAppMessage 函数 推测应该是 megalo 内部实现导致的
- 版本
```json
    "@megalo/entry": "^0.1.1",
    "@megalo/env-plugin": "^1.0.1",
    "@megalo/target": "^0.6.3",
    "@megalo/template-compiler": "^0.8.0",
    "@megalo/vhtml-plugin": "^0.1.2",
    "megalo": "^0.8.0",
    "octoparse": "^0.3.2",
```
megalo 0.7.7也存在同样的情况
- 操作系统信息
macOS 10.14.1

**Comment by elcarim5efil** [comment]
默认都会绑定这个方法，可以考虑根据是否提供该方法决定是否为页面绑定该方法。
