### ISSUE TITLE
小程序  背景图片base64处理怎么不生效

### ISSUE THREAD

**Issue by meikang123** [kaola-fed/megalo#176]
{
              test: /\.(png|jpg|gif)$/i,
              use: [
                  {
                      loader: 'url-loader',
                      query: {
                          limit: 50000,
                          name: '/static/img/[name].[ext]'
                      }
                  }
              ]
          }

**Comment by elcarim5efil** [comment]
demo 的测试代码看是正常的，可以现在 demo 仓库里修改试试。

**Comment by meikang123** [comment]
每一个页面是单独的vue  这个意义在哪里  还有我创建页面没创建vue实例貌似也是行的通的

**Comment by elcarim5efil** [comment]
例如商品详情页，打开商品 A 后通过页面中的其他链接进入到商品 B，这个时候需要重新创建一个 Vue 实例存储新的数据。如果还是同一个 Vue 实例，商品 B 的数据会把商品 A 覆盖了，从商品 B 返回到商品 A 时，展示的还是商品 B 的数据。

**Comment by meikang123** [comment]
那就是不是公用的页面或者组件  就没必要vue实例吗

**Comment by elcarim5efil** [comment]
````javscript
Page({
  onLoad() {}
})
```

**Comment by meikang123** [comment]
好吧  谢谢   我在研究研究
