### ISSUE TITLE
编译时直接退出

### ISSUE THREAD

**Issue by y213140** [kaola-fed/megalo#177]
npm run dev:wechat

> Nyh_all@0.0.0 dev:wechat G:\work\Nyh_all
> webpack --config ./build/webpack.config.wechat.js -w

webpack is watching the files…

PS G:\work\Nyh_all>

编译时直接退出？

**Comment by bigmeow** [comment]
@y213140   先暂时锁死版本，"@megalo/target": "0.5.7"
https://github.com/megalojs/megalo-cli-service/issues/2

**Comment by bigmeow** [comment]
target 升级到最新版 0.7.1或者以上， 已经解决该问题
