### ISSUE TITLE
混合开发的一些问题

### ISSUE THREAD

**Issue by wty625073563** [kaola-fed/megalo#178]
微信小程序：
根目录下utils目录有一个公用的JS。
App.vue需要引用该JS中封装的方法。
`import user from '@/utils/user'`
假设 方法是用户登陆的一系列操作，然后登陆成功后把用户信息存储到user.js里面

static/components，微信的自定义组件下也引用该js。
`import user from '../../../utils/user'`

而我看到编译之后，实际上他们不是引用同一个js的。
所以我拿不到用户登录后的信息。

我有想过使用vuex来进行管理，但是在微信的自定义组件下的又怎么使用呢？
（至于为什么要使用微信自定义组件，是因为这些都是从旧项目中搬过来的，而且数目比较多，而目前时间成本并不允许全部改为vue的组件）

上面类似的登陆问题只是其一，还有其他的类似的问题，比如，**状态的监听**等。

有什么办法解决这些问题呢？

**Comment by goldlin** [comment]
一个想法： vuex里管理状态的同时同步存储到storage，自定义组件下从storage实时取值

**Comment by elcarim5efil** [comment]
storage 是一个思路，应该也可以挂载到 App 上，通过 globalData 进行访问。
