### ISSUE TITLE
微信头像通过v-if切换 第二次img绑定不了？

### ISSUE THREAD

**Issue by meikang123** [kaola-fed/megalo#188]
![qq 20190228120557](https://user-images.githubusercontent.com/16129828/53540609-3808c780-3b51-11e9-8f69-f2bbf08d0b32.png)
![qq 20190228120708](https://user-images.githubusercontent.com/16129828/53540660-62f31b80-3b51-11e9-9999-d7496e1a34d6.png)

**Comment by elcarim5efil** [comment]
- megalo@0.9.0-0
- @megalo/template-compiler@0.9.0-0

**Comment by meikang123** [comment]
好

**Comment by meikang123** [comment]
可以了  这个打包后  开发者工具里面appData  没法看   有这方面配置吗

**Comment by elcarim5efil** [comment]
调试工具我们在调研了

**Comment by meikang123** [comment]
![qq 20190228201127](https://user-images.githubusercontent.com/16129828/53565777-4e387700-3b95-11e9-861b-e10ac751aeb8.png)
换了新包  打包会有不同的错误了

**Comment by elcarim5efil** [comment]
本地没有复现这样的问题，看着像是页面路径配置有问题
