### ISSUE TITLE
入口文件[src/index.js]引入小程序插件，构建工具会报错

### ISSUE THREAD

**Issue by auven** [kaola-fed/megalo#189]
- 代码与复现步骤，**可复现代码片段**或**最小可复现代码仓库链接**

src/index.js
``` js
...
export default {
  config: {
    ...
    usingComponents: {
      'map-route': 'plugin://myPlugin/mapRoute'
    }
  }
}
```

- 问题现象

控制台报错如下：
![image](https://user-images.githubusercontent.com/23731087/53542373-275c4f80-3b59-11e9-994c-3975b2d08b94.png)
![image](https://user-images.githubusercontent.com/23731087/53542450-7b673400-3b59-11e9-98c9-ef1d800b0487.png)

- 版本，包括 `@megalo/target`、`megalo`(`@megalo/template-compiler`，应该与 `megalo` 版本相匹配)。如果不是最新版本，建议更新到最新版再试试，说不定已经修复。

![image](https://user-images.githubusercontent.com/23731087/53542549-e44eac00-3b59-11e9-8cfb-e30443674c4e.png)

- 操作系统信息 `mac`

我看了一下，是这个正则导致的错误，https://github.com/megalojs/megalo-entry/blob/978381a92348dd342d7456343b17e06316335bd5/lib/util.js#L5

`/\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\/|\/\/[^\r\n]*|\s/g` 解析 `'map-route': 'plugin://myPlugin/mapRoute'` 后成了 `'map-route':'plugin:` ，导致 `json5.parse(txt.substring(begin,end+1))` 报错。

正则我不会写，望大佬们尽快处理~

**Comment by elcarim5efil** [comment]
@megalo/entry@0.1.2
