### ISSUE TITLE
例子中，src下面的htmlparse 目录下的文件有什么作用，删除后，build后的小程序会报错

### ISSUE THREAD

**Issue by js5323** [kaola-fed/megalo#19]
请问例子中，`./src/htmlparse` 目录下的文件有什么作用，里面的两个文件都是空文件，删除后build的小程序运行会报错
````
Error:
in File: ./app.wxss

File not found: ./htmlparse/index.wxss
编译 .wxss 文件错误，错误信息如上，可在控制台查看更详细信息
````

**Comment by js5323** [comment]
> 创建 webpack target 的时候不需要传入 htmlParse 字段来指定解析库。

请问具体参数怎么配置，目前是这么写的：
````
module.exports = {
  target: createMegaloTarget({
    compiler: Object.assign(compiler, {}),
    platform: 'wechat',
  }),
  ...
}
````

**Comment by elcarim5efil** [comment]
这样配置应该是可以的，你现在的配置是参考 [megalo-demo](https://github.com/kaola-fed/megalo-demo) 的吗？这个例子 src 下是没有这个文件夹了。

**Comment by js5323** [comment]
我是参考 [工程实例](https://github.com/kaola-fed/megalo-examples)的，这个例子会出现相关问题

**Comment by elcarim5efil** [comment]
明白了，这个 repo 的依赖没有更新，我们稍后更新一下。sorry。

请先参考 [megalo-demo](https://github.com/kaola-fed/megalo-demo) 里的例子。

**Comment by elcarim5efil** [comment]
exmaples 已经更新。

**Comment by js5323** [comment]
已经解决，谢谢你 ！ @elcarim5efil
