### ISSUE TITLE
编译出的自定义tabbar组件无效

### ISSUE THREAD

**Issue by pigzzz123** [kaola-fed/megalo#197]
根据小程序官方文档，自定义tabbar组件，需在根目录添加 tabBar [代码文件，详见](https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html)
![default](https://user-images.githubusercontent.com/24596908/53708636-53d0de00-3e6f-11e9-9bbb-56ec37ed0bb0.png)
![default](https://user-images.githubusercontent.com/24596908/53708647-64815400-3e6f-11e9-910e-23f89f7c3b72.png)
图一为自定义tabbar源文件，也在dist-wechat下成功编译成了custom-tab-bar。
但在预览中无效，也无报错。经过调试，貌似是data定义内的变量并没有用，导致tabbar高度为0，不可见

**Comment by auven** [comment]
你好，看一下你打包后的 `dist-wechat/custom-tab-bar/index.json` 这个文件的内容，看是否有
``` json
{
  "component": true
}
```
自定义 tabbar 必须是一个自定义组件

**Comment by pigzzz123** [comment]
> ```json
> "component": true
> ```

有的，已经在config内写了，但效果还是一样没有出来

**Comment by pigzzz123** [comment]
> 
> 
> 你好，看一下你打包后的 `dist-wechat/custom-tab-bar/index.json` 这个文件的内容，看是否有
> 
> ```json
> {
>   "component": true
> }
> ```
> 
> 自定义 tabbar 必须是一个自定义组件

有的，已经在config内写了，但效果还是一样没有出来

**Comment by auven** [comment]
会不会微信开发者工具版本太低？

**Comment by pigzzz123** [comment]
> 
> 
> 会不会微信开发者工具版本太低？

用的是最新的v1.02.1902010，微信基础库是2.6.1
![default](https://user-images.githubusercontent.com/24596908/53718118-4b8b9980-3e95-11e9-8cc6-53c7c802d94f.png)
![default](https://user-images.githubusercontent.com/24596908/53718124-52b2a780-3e95-11e9-8623-e29cb04ff48f.png)

**Comment by pigzzz123** [comment]
> 
> 
> 会不会微信开发者工具版本太低？

我直接在模板内写死，就是正常的效果，但还是调用不了自定义的switchTab方法
![default](https://user-images.githubusercontent.com/24596908/53718767-20a24500-3e97-11e9-87e5-995cd6b98f04.png)
![default](https://user-images.githubusercontent.com/24596908/53718816-43345e00-3e97-11e9-979e-94aad5e02b05.png)
所以猜测自定义tabbar组件下的script标签下的变量，事件方法都是无效的

**Comment by auven** [comment]
我猜测：应该是 megalo 不支持将 `vue` 转化为微信自定义组件，目前只支持转化为页面，即使写了 `component: true` ，打包出来的还是页面级的，自定义组件的相关生命周期都没有打包进去。

所以建议自定义组件用原生的方式写，我的自定义 tabbar 就是原生写的。

**Comment by pigzzz123** [comment]
> 
> 
> 我猜测：应该是 megalo 不支持将 `vue` 转化为微信自定义组件，目前只支持转化为页面，即使写了 `component: true` ，打包出来的还是页面级的，自定义组件的相关生命周期都没有打包进去。
> 
> 所以建议自定义组件用原生的方式写，我的自定义 tabbar 就是原生写的。

好吧，目前也只能这样做了，谢谢您耐心的解答

**Comment by elcarim5efil** [comment]
目前还是以 template 的方式实现的，小程序原生自定义组件实现的方案我们也有计划尝试。tabBar 目前还是用小程序自定义组件做吧。

另外感谢 @pigzzz123 的热心解答。

**Comment by pigzzz123** [comment]
> 
> 
> 目前还是以 template 的方式实现的，小程序原生自定义组件实现的方案我们也有计划尝试。tabBar 目前还是用小程序自定义组件做吧。
> 
> 另外感谢 @pigzzz123 的热心解答。

嗯嗯，已经用回原生的了，老哥好像艾特错了人，哈哈

**Comment by elcarim5efil** [comment]
哈哈，😅。
感谢  @auven 热心解答。
