### ISSUE TITLE
脚手架初始化下来的项目会报错

### ISSUE THREAD

**Issue by sanriqing** [kaola-fed/megalo#198]
megalo 初始化下来，项目会报vue 和vue-template-complier 不匹配。修改为匹配版本或删除均无效果。

**Comment by sanriqing** [comment]
初步排查安装 vue-cropper 之后会复现

**Comment by auven** [comment]
[vue-cropper](https://github.com/xyxiao001/vue-cropper) 不支持小程序端

**Comment by elcarim5efil** [comment]
vue 和 vue-template-compiler 用不到的，可以去掉
