### ISSUE TITLE
如何用正确的姿势使用 createSelectorQuery ？？？

### ISSUE THREAD

**Issue by Kidwind** [kaola-fed/megalo#200]
数据从服务器端异步载入，载入成功后渲染页面，页面渲染完成后，需要调用 createSelectorQuery 来实现一些效果，现在的问题是我在什么时机才能保证页面已经渲染完成后调用 createSelectorQuery？
微信小程序的 1.5.0 版本在 setData 方法中加了个回调方法（ https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/page.html#pageprototypesetdataobject-data-function-callback ），可以保证在页面渲染完成后调用，但用了 megalo 框架，就不知道该怎么实现了，现在用 setTimeout 来延迟，感觉太弱。

**Comment by zhengzhaozhao** [comment]
没有类似支付宝小程序onReady的钩子吗

**Comment by Kidwind** [comment]
@zhengzhaozhao 数据是异步从服务器载入的啊，并不是写死在页面上的，所以 onReady 的时候相关的节点还没创建呢。

**Comment by elcarim5efil** [comment]
从框架层面，暂时还没有一个很好且准确的方式，建议可以封装一个自动重试逻辑的节点获取方法。
1. 首次获取，如果成功则返回结果
2. 如果失败，50ms（默认 50ms 清空数据 buffer） 后再尝试，直至成功获取或者超过重试次数
3. 整个方法用回调或 Promise 的方法返回结果
