### ISSUE TITLE
单vue文件怎么使用Vant Ui

### ISSUE THREAD

**Issue by jifeilong9** [kaola-fed/megalo#205]
官网文档示例是js+vue多文件引入vant,单个vue文件的怎么引入？

**Comment by mosquito1803** [comment]
使用方法是一样的 单文件组件中script部分即对应js部分 如不清楚vue的单文件组件使用可以参考[vue的官方文档](https://cn.vuejs.org/v2/guide/single-file-components.html) megalo中页面的配置注入参考[页面 - Page](https://megalojs.org/#/config/page)

**Comment by jifeilong9** [comment]
vant weapp是小程序的ui不知道怎么参考vue官网的文档,并且我根据megalo官方文档添加依然保存，能给个demo吗？
![image](https://user-images.githubusercontent.com/24316291/54125991-7354a180-4441-11e9-9d55-09804719140e.png)

**Comment by auven** [comment]
可以参考这个 [zlxbuzz/megalo-vant](https://github.com/zlxbuzz/megalo-vant) ，以 `usingComponents` 的方式引入：
``` js
config: {
  usingComponents: {
    'van-button': '/static/vant/button/index',
    'van-action-sheet': '/static/vant/action-sheet/index',
  },
}
```

目前微信小程序支持全局引入第三方小程序组件，所以你也可以直接在 megalo 入口文件 `index.js` 里引入
![image](https://user-images.githubusercontent.com/23731087/54168596-48eafe80-44aa-11e9-8381-0788e4a50812.png)

**Comment by jifeilong9** [comment]
谢谢，已经可以了用了
