### ISSUE TITLE
[Bug] 嵌套组件导致的各种诡异的 bug

### ISSUE THREAD

**Issue by auven** [kaola-fed/megalo#208]
这个是我在实际项目中遇到的问题，这里在 megalo-demo 里简单的复现。

**简化如下：**

`组件A`：
```
<标签>
  <组件B/>
  <组件C/>
  <slot />
</标签>
```

如果 `组件A` 的 `slot` 里出现了 `组件A` 里有过的组件 （`组件B` 或 `组件C`） ，就会出现各种诡异的 bug ，例如：

```
<组件A>
  <组件B/>
</组件A>
```

##  代码

> 基于最新的 [megalo-demo](https://github.com/kaola-fed/megalo-demo)。

### 首先创建三个组件

- `src/components/CompA.vue`

``` vue
<template>
  <div style="margin: 20px; border: 1px solid #ccc;">
    <div>组件A</div>
    <div>count：{{ count }}</div>
    <div @click="clickA1">点击我，方法名为（clickA1）</div>
    <div @click="clickA2">点击我，方法名为（clickA2）</div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      count: 0
    }
  },
  methods: {
    clickA1() {
      this.count++
      console.log("A组件--clickA1");
    },
    clickA2() {
      this.count--
      console.log("A组件--clickA2");
    }
  }
};
</script>

<style>
</style>
```

- `src/components/CompOther.vue`

``` vue
<template>
  <div style="margin: 20px; border: 1px solid #fd6440;">
    <div>其他组件(<slot></slot>)</div>
    <div>所在位置：{{ weizhi }}</div>
    <div @click="click">点击我：{{ count }}</div>
  </div>
</template>

<script>
export default {
  props: {
    weizhi: {
      type: String,
      default: ""
    }
  },
  data() {
    return {
      count: 0
    }
  },
  methods: {
    click() {
      this.count++
      console.log('其他组件的点击事件')
    }
  }
};
</script>

<style>
</style>
```

- `src/components/BasePage.vue`

``` vue
<template>
  <div class="base-page">
    <!-- 可以尝试把下面三个互换位置，会产生不同的 bug 。。。 -->
    <comp-other weizhi="BasePage 组件里">BasePage 组件里</comp-other>
    <comp-a />
    <slot></slot>
  </div>
</template>

<script>
import CompA from "./CompA"
import CompOther from './CompOther'
export default {
  props: {
    name: {
      type: String,
      default: '名字'
    }
  },
  components: {
    CompA,
    CompOther
  }
};
</script>

<style>
</style>
```

### 修改 `src/pages/index/index.vue`

``` vue
<template>
  <base-page class="app">
    <comp-other weizhi="index 页面里">index 页面里</comp-other>
  </base-page>
</template>

<script>
import BasePage from "@/components/BasePage"
import CompOther from '@/components/CompOther'

export default {
  components: {
    BasePage,
    CompOther
  }
}
</script>

<style lang="less" scoped>
.list {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: stretch;
  &__item {
    padding: 10px;
    color: blue;
  }
}
</style>
```

### 情况一

`BasePage.vue`
``` vue
<template>
  <div class="base-page">
    <slot></slot>
    <comp-other weizhi="BasePage 组件里">BasePage 组件里</comp-other>
    <comp-a />
  </div>
</template>
```

出现现象：
![image](https://user-images.githubusercontent.com/23731087/54409191-7b059600-4720-11e9-8a3d-4713d332f05a.png)

### 情况二

`BasePage.vue`
``` vue
<template>
  <div class="base-page">
    <slot></slot>
    <comp-a />
    <comp-other weizhi="BasePage 组件里">BasePage 组件里</comp-other>
  </div>
</template>
```

出现现象：
![image](https://user-images.githubusercontent.com/23731087/54409269-dfc0f080-4720-11e9-93a5-b222f3be8765.png)

### 情况三

`BasePage.vue`
``` vue
<template>
  <div class="base-page">
    <comp-other weizhi="BasePage 组件里">BasePage 组件里</comp-other>
    <comp-a />
    <slot></slot>
  </div>
</template>
```

出现现象：
![image](https://user-images.githubusercontent.com/23731087/54409346-5cec6580-4721-11e9-9ad5-25c4c0699f82.png)

## 版本

- @megalo/target@0.6.3 
- @megalo/template-compiler@0.8.0
- megalo@0.8.0 

## 操作系统信息

mac 10.14.3

**Comment by auven** [comment]
另外还出现了一个不知道啥情况的 bug (捂脸.jpg)。

![image](https://user-images.githubusercontent.com/23731087/54415666-e870f100-4737-11e9-9be9-00f88f48de89.png)

这是我的 `BasePage.vue` 组件
![image](https://user-images.githubusercontent.com/23731087/54415705-06d6ec80-4738-11e9-9e36-089764cc9214.png)

**Comment by auven** [comment]
### 还有这个莫名其妙的问题，请看截图

![image](https://user-images.githubusercontent.com/23731087/54472839-58e84280-480a-11e9-9f6c-4e0d4ea682d5.png)

### 没加代码前

![WechatIMG45](https://user-images.githubusercontent.com/23731087/54472856-a795dc80-480a-11e9-9c53-7853d51cc002.png)

### 加了代码后正常了

![WechatIMG46](https://user-images.githubusercontent.com/23731087/54472849-7e754c00-480a-11e9-939d-d06093298c5c.png)

**Comment by elcarim5efil** [comment]
试过 0.9.0-4 吗？在这个版本对 slot 内部事件的问题有修改。数据异常的问题我在看一下。

**Comment by elcarim5efil** [comment]
问题定位了，正在修复，晚点发个测试版

**Comment by auven** [comment]
感谢大佬~

**Comment by elcarim5efil** [comment]
试试 0.9.1-0。
问题原因是，slot 内部的 CompOther 和 BasePage 内部的 CompA 或者 CompOther 重复了（id 设置逻辑时，组件在组件树中先序遍历的顺序赋予递增 id，出问题的组件 id 和别的组件 id 重了），所以数据串了，或者事件处理方法找不到。解决方法时，给 slot 内部的组件定义 id 时加入一个前缀 `s` ，用以区别。

**Comment by auven** [comment]
@elcarim5efil  可以了，谢谢哈~

**Comment by unclexiao** [comment]
我也遇到了相同的问题，果然更新一下版本就好了，谢谢大佬们🙏 @elcarim5efil
