### ISSUE TITLE
请问megalo中如何使用插件，例如图表插件 f2-canvas

### ISSUE THREAD

**Issue by js5323** [kaola-fed/megalo#21]
需要使用一些第三方的组件库，例如，[f2-canvas](https://github.com/antvis/f2-canvas)
按照其文档使用没有效果，请问是否需要其他特别的配置？

**Comment by b2nil** [comment]
@js5323 

只是针对 f2-canvas 的话，可以首先做一些手动准备工作：
- 在 dist 目录下建一个 `node_modules` 目录
- 在 dist 里面直接使用 npm 安装 f2-canvas
- 使用小程序开发工具的构建 npm 功能将其自动构建到 `miniprogram_npm` 目录下

然后在具体 page 的 index.js 里面引入组件：
```javascript
export default {
  config: {
    navigationBarTitleText: "F2 Charts Demo",
    usingComponents: {
      'ff-canvas': "@antv/f2-canvas"
    }
  }
}
```
f2-canvas 有些坑（具体看文档和相关 issue ），跳过去就可以正常使用了。

![f2](https://user-images.githubusercontent.com/16893585/47965944-ce3b4e00-e087-11e8-8f65-451e8bcb6bbd.png)

**Comment by js5323** [comment]
@b2nil   感谢回答
在dist目录中再去构建使用原生组件觉得比较麻烦，我的处理方式是用F2包装一个针对小程序的vue组件去使用
