### ISSUE TITLE
组件中slot中使用if判断不生效

### ISSUE THREAD

**Issue by fukai7722** [kaola-fed/megalo#211]
平台：微信小程序
版本：0.8.0
代码：
`
<slot name="brief">
     <div v-if="brief">
            <text class="am-list-content-brief">{{brief}}</text>
     </div>
  </slot>`

问题
组件中slot中使用if判断，符合条件的if指令不能显示对应的元素

**Comment by elcarim5efil** [comment]
更新到 0.9.0 试试

**Comment by mosquito1803** [comment]
我这边用0.9.0的表现是，去掉v-if部分，插值中的brief是正常显示的，但是使用v-if之后，v-if拿到的brief值貌似有问题，所以无法正常渲染
```
<slot name="brief"> 
  <div v-if="brief"> 
    <text class="am-list-content-brief">{{brief}}</text> 
  </div> 
</slot>
```
