### ISSUE TITLE
在真机调试模式下真机上的组件不显示

### ISSUE THREAD

**Issue by y213140** [kaola-fed/megalo#212]
<div class="flex center">
      <mainsearch :way="way" v-on:focusInput="onInput" v-on:searchList="searchList"></mainsearch>
    </div>

 import mainsearch from "@/components/search/main"

components: {
      mainsearch,
      shoplist
    },

在开发者工具上好好的 但是在真机上无法显示界面

![a'a微信截图_20190319112629](https://user-images.githubusercontent.com/28527096/54578326-54a26c00-4a3a-11e9-8230-7cd37ec358e0.png)
![微信图片_20190319113033](https://user-images.githubusercontent.com/28527096/54578357-713ea400-4a3a-11e9-80c1-9d3c5c8e3376.png)

**Comment by elcarim5efil** [comment]
请提供可复现的代码，这样无法定位问题。

**Comment by y213140** [comment]
无意间解决了这个问题， 这个搜索组件是在分包内的不显示 ，在主包内显示正常
这是为什莫
![微信截图_20190320121413](https://user-images.githubusercontent.com/28527096/54658697-b382e680-4b09-11e9-8da6-92f98842e3cd.png)

但是将search文件放到分包的pagesShop下的pages文件夹下就在真机上无法显示

**Comment by y213140** [comment]
![a微信截图_20190320121613](https://user-images.githubusercontent.com/28527096/54658777-1ffde580-4b0a-11e9-8453-8b4effd50b7f.png)

**Comment by elcarim5efil** [comment]
@megalo/target 的版本是多少？组件是在主包还是分包内定义的？如果是在分包内定义，主包中的页面是无法正常使用分包中的组件的。

**Comment by y213140** [comment]
"@megalo/target": "^0.6.2",
   组件是在主包和分包外的定义的
![微信截图_20190320141721](https://user-images.githubusercontent.com/28527096/54663025-e8e40000-4b1a-11e9-861e-83d2055435a1.png)

**Comment by elcarim5efil** [comment]
试试更新到最新版本，`@megalo/target@0.7.0`。

**Comment by y213140** [comment]
版本更新后还是这样
