### ISSUE TITLE
onPageScroll不触发和临时解决方案

### ISSUE THREAD

**Issue by hiNISAL** [kaola-fed/megalo#214]
目前的尝试在页面级别的组件中使用onPageScroll，没有任何响应。

我这边的环境是使用了TypeScript，不知道是不是会有联系。

不过摸索中想到了一个解决办法，并且已经验证可行。

通过微信小程序自带的`getCurrentPages`api或者通过`@megalo/api`提供的`getCurrentPages`，拿到页面栈，然后拿到当前的`Page`实例。

`Page`实例上有所有的钩子，在vue组件走到`created`或者`mounted`的时候，改掉上面的`onPageScroll`即可。

```
<script lang="ts">
import { Vue, Component } from 'vue-property-decorator';

@Component
export default class Home extends Vue {
  mounted() {
    Megalo.getCurrentPages().pages.pop().onPageScroll = ({ scrollTop }) => {
      console.log(scrollTop);
    };
  }
}
</script>
```

这样可以暂时性解决这个问题。

**Comment by elcarim5efil** [comment]
ts 需要另外注册钩子，[参考](http://megalojs.org/#/senarios/typescript)

**Comment by hiNISAL** [comment]
OK 已解决 谢谢
