### ISSUE TITLE
微信小程序上线的体验版直接进入某个页面报错

### ISSUE THREAD

**Issue by y213140** [kaola-fed/megalo#222]
![微信图片_20190323093231](https://user-images.githubusercontent.com/28527096/54860020-0dc0b900-4d4f-11e9-9fdd-b32a99f6581c.png)

**Comment by mosquito1803** [comment]
看下打包出来的内容里面有没有这个文件？

**Comment by y213140** [comment]
打包出来的有  并且如果正常进入是正常的 但是直接进入小程序的某个详情页面时就报错了
正常的进入：
![微信图片_20190323100113](https://user-images.githubusercontent.com/28527096/54860268-aad12100-4d52-11e9-9e0b-09850ed2aaef.jpg)
![微信图片_20190323100118](https://user-images.githubusercontent.com/28527096/54860271-af95d500-4d52-11e9-8d7a-20075ec0e776.jpg)

**Comment by mosquito1803** [comment]
其他页面没有引用这个依赖吗 这个vendor是你手动引用的还是打包阶段添加的？

**Comment by y213140** [comment]
打包的时候添加的

**Comment by mosquito1803** [comment]
如果其他页面都引用了这个依赖  不应该只是这个页面出问题  麻烦具体比较下详情页和其他页面引用的js区别 或者能提供下截图/文件 现在的信息太少了 没法判断问题哈

**Comment by y213140** [comment]
解决了  详情页是在分包内的时候不行  必须在主包内  这是个BUG吧  谁来解决下？

**Comment by wty625073563** [comment]
有可能是因为你微信上传的时候勾选了 “上传时进行代码保护”

**Comment by y213140** [comment]
不是上传的问题 是在分包内的详情页面直接打开时编译的vendor.js文件路径是绝对路径 读不到
