### ISSUE TITLE
Megalo是否支持typescript

### ISSUE THREAD

**Issue by zzzzzshPig** [kaola-fed/megalo#224]
请问Megalo当前解析Vue文件是否支持解析script[lang=ts]，配置了Ts版本的Megalo发现dist无法生成小程序需要的文件，只能生成Component。如果无法解析，请问后续有支持的计划吗？谢答~

**Comment by bigmeow** [comment]
一直支持的，零配置版本这一两天会放出来。着急的你可以先到这里体验: https://github.com/bigmeow/megalo-cli/tree/master/example/project02
注意： target0.5.7版本编译组件会有问题.

**Comment by zzzzzshPig** [comment]
对，我就是0.5.7版本的，我发现原因在于 loaderContext.megaloDeferred 返回的Promise没有决策，所以既没有then，也没有catch。如果将vue文件的script的lang属性去掉，则then调用，但是返回的data并没有page，只有component，所以无法输出page。官网的demo也有这个问题。

**Comment by zzzzzshPig** [comment]
我可以升级target来解决这个问题吗

**Comment by bigmeow** [comment]
可以。就是开发时编译报错会不显示，bug解决前算是鱼与熊掌不可兼得吧

**Comment by zzzzzshPig** [comment]
我去试试，谢谢

**Comment by bigmeow** [comment]
最新的cli 已经支持，target也解决了相关问题，可以关issure了
@zzzzzshPig
