### ISSUE TITLE
async/await 在megalo-cli 1.6.1版本中使用报错

### ISSUE THREAD

**Issue by centuryHarbour** [kaola-fed/megalo#235]
![image](https://user-images.githubusercontent.com/20835837/55319500-9655fc80-54a7-11e9-86b2-6a5223200bcb.png)
![image](https://user-images.githubusercontent.com/20835837/55319513-9ce47400-54a7-11e9-9595-f9567e1f4e3a.png)

**Comment by bigmeow** [comment]
把小程序自带的开发者工具 `es6 转es5`  勾选去掉

**Comment by centuryHarbour** [comment]
> 把小程序自带的开发者工具 `es6 转es5` 勾选去掉

好了

**Comment by auven** [comment]
@bigmeow   如果必须开启 `es6 转 es5` 的怎么办，我因为在项目中使用了 `vant-weapp` 必许开启

**Comment by bigmeow** [comment]
@auven  临时先这么解决：

![image](https://user-images.githubusercontent.com/10484248/55716957-d62e5e00-5a2a-11e9-9910-69f405237262.png)

node_modules目录下  找到这个包 干掉红色的代码

https://github.com/megalojs/megalo-cli/issues/27

**Comment by auven** [comment]
好的，感谢大佬~ 我看了一下 `vant-weapp` 在最新的 [`0.5.9`](https://youzan.github.io/vant-weapp/#/changelog) 版本中已经支持不开启 `es6 转 es5` 了。不过 `megalo-cli` 最好是不要限制是否勾选。
