### ISSUE TITLE
如何引用全局 wxss？

### ISSUE THREAD

**Issue by imyellow** [kaola-fed/megalo#236]
在从 mpvue 迁移过来，mpvue 在 main.js 内直接写
```
import './static/vant/common/index.wxss'
import './static/animate.wxss'
```
引用小程序原生组件的 wxss 文件
在 megalo 中要怎么写呢

**Comment by bigmeow** [comment]
后缀改成.css文件

**Comment by imyellow** [comment]
> 后缀改成.css文件

不行，微信组件的文件是直接复制到微信包里的，里面 @import 关联的也都是 wxss，改扩展名不现实

**Comment by bigmeow** [comment]
我可以在cli 处理下 让其默认支持 `.wxss` 扩展，当成普通css处理
不过感觉还是可能有问题  有些小程序独有的css 选择符  不知道会不会报错

**Comment by bigmeow** [comment]
你可以吧它的wxss 拷贝出来，复制一份改成.css后缀

**Comment by auven** [comment]
@imyellow  你也可以手动修改一下项目的配置，以下是使用 megalo 最新的 cli 生成的项目

![image](https://user-images.githubusercontent.com/23731087/55473906-655dff00-5642-11e9-8f45-19b4cc4bc469.png)
