### ISSUE TITLE
头条小程序无法编译

### ISSUE THREAD

**Issue by JH46666** [kaola-fed/megalo#237]
current version:    0.3.2 
"octoparse": "^0.3.2"

**Comment by JH46666** [comment]
megalo-cli-service serve --platform toutiao 
无法编译出头条小程序

**Comment by bigmeow** [comment]
cli 还未支持

**Comment by JH46666** [comment]
> cli 还未支持

手动怎么配置呢

**Comment by bigmeow** [comment]
已经支持,早上测试完再发版

**Comment by bigmeow** [comment]
@megalo/cli-service 1.0.0-alpha.18 已支持编译头条小程序，需要 @megalo/target 0.70或更高版本,
megalo 0.9.0或更高版本支持
@JH46666
