### ISSUE TITLE
[bug] onPageScroll、onPullDownRefresh、onReachBottom等生命周期函数无法在ts中被触发

### ISSUE THREAD

**Issue by bigmeow** [kaola-fed/megalo#242]
- 复现： 使用 cli 生成 typescript 项目，在页面vue文件加入下列代码可复现：
``` js
onPageScroll () {
    console.log('滚动')
}
```
- 问题现象:  函数不会被触发
- megalo 0.10版本能复现，但0.9.0版本正常
- 操作系统信息: mac os

**Comment by mosquito1803** [comment]
@elcarim5efil  发现使用ts时[这里](https://github.com/kaola-fed/megalo/blob/master/src/platforms/mp/runtime/lifecycle/page.js#L70)的小程序生命周期在`vueOptions.options.extendOptions`上
