### ISSUE TITLE
megalo不支持最新版本的vue-loader, 目前支持到15.4.0

### ISSUE THREAD

**Issue by wangzhengbo** [kaola-fed/megalo#248]

**Comment by elcarim5efil** [comment]
目前还没有升级，以后可能会跟进，用现在的版本应该问题也不大吧。

**Comment by wangzhengbo** [comment]
对，现在的也够用。曾经用了最新版本的vue-loader导致megalo服务启动不起来，错误信息还不明显，浪费了很多时间去解决这个问题。对于喜欢使用最新版本依赖的用户，很容易会犯和我一样的错

**Comment by elcarim5efil** [comment]
我们在文档里面提示一下对于的 vue-loader 版本吧。
