### ISSUE TITLE
将数据绑定到Vue实例上，没有效果吗

### ISSUE THREAD

**Issue by QzhouZ** [kaola-fed/megalo#25]
//  index.js里
    加入Vue.prototype.$app = 'test'

    // page 里使用
    created () {
      console.log(this.$app) // 结果为undefined
     }

**Comment by zwwill** [comment]
同页面吗？

**Comment by QzhouZ** [comment]
ok了，更新了新版本就正常了

**Comment by QzhouZ** [comment]
@zwwill 不同页面能共用吗

**Comment by zwwill** [comment]
可以放在 globalDate里

**Comment by sunnyboyi** [comment]
> 可以放在 globalDate里
我昨天用Demo 试了下发现 取到的globalData 是undefined  是啥原因？
var appInstance = getApp()
this.globalData = appInstance.globalData;

其中 appInstance.globalData 显示 undefined

**Comment by zwwill** [comment]
@sunnyboyi 要用megalo 0.2.0 以上版本

**Comment by sunnyboyi** [comment]
> @sunnyboyi 要用megalo 0.2.0 以上版本

好我回头试试  我昨天是直接拉的 kaola-fed/megalo-demo 代码 发现有问题  没注意看版本
