### ISSUE TITLE
老版本升级新版本后，slot不能生效了，事件冒泡不能生效，添加事件捕获后，点击内部元素事件不会生效

### ISSUE THREAD

**Issue by JokerLoLgrey** [kaola-fed/megalo#252]
```js
// 这是老版本package.json文件
```
![image](https://user-images.githubusercontent.com/33446705/57426749-24659580-7253-11e9-958f-6d3754986eac.png)
```js
// 这是新版本package.json文件
```
![image](https://user-images.githubusercontent.com/33446705/57426791-668ed700-7253-11e9-80ed-b26cb57cc3ac.png)

```js
 新版slot不能和v-if一起使用（内部包裹一层可暂时解决）
```

```js
 // 事件冒泡和事件捕获代码如下
```
![image](https://user-images.githubusercontent.com/33446705/57427242-a48cfa80-7255-11e9-8998-c0d3146c5e31.png)
```js
之前这么写是没有问题的，新版本的问题是，
只会执行event事件，titleEvent事件和imgEvent事件是如何都不会执行，
把阻止捕获和阻止冒泡去掉暂时可用，但是就必须同时声明3个函数，不希望执行的函数只能这样声明() => {}

```

**Comment by elcarim5efil** [comment]
最新版本应该是修复关了 slot 相关问题，能否确定 node_modules 中包的版本为最新。

```html
<template>
  <div>
    <CompA :color="color" test="sss" @test="test">
      <template v-slot="{ test }" v-if="count % 2">
        <CompB>{{ test.name }}</CompB>
      </template>
    </CompA>
    <button @click="count++">add count</button>
  </div>
</template>
```

.stop 在小程序中会转换成 catch，.capture 会转换成 capture-bind，.stop.capture 会转换成 capture-catch，可以参考 [小程序事件文档](https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxml/event.html)对比一下。

**Comment by JokerLoLgrey** [comment]
> .stop.capture

我看了，貌似不能到达我的需求，只好用v-if解决了
