### ISSUE TITLE
大量列表数据渲染性能问题?

### ISSUE THREAD

**Issue by phoenixsky** [kaola-fed/megalo#256]
从mpvue移植过程中,返现页面有大量列表需要渲染时,性能很慢.同样2600多条的存在本地的火车站列表数据.
mpvue框架下渲染不到2秒.
megalo框架下渲染大约8秒.

单独一个v-for在android设备也要好久.
![image](https://user-images.githubusercontent.com/6359214/57514287-b7c9c400-7342-11e9-8dd4-2b7c6d0dcced.png)

**Comment by elcarim5efil** [comment]
将列表 item 封装成组件试试呢？由于底层数据结构的问题，长列表在小程序中做 diff 性能较差。将 item 抽离成组件有帮助。
