### ISSUE TITLE
微信小程序方法调用问题

### ISSUE THREAD

**Issue by microyulive** [kaola-fed/megalo#257]
本人菜鸟，求问：
1. Vue文件中，this.setData如何调用?这个this不太清楚是用的哪个对象。。。
2. Vue文件中，wx.createAnimation()这类需要在html对应的标签中绑定类似animation="animation"参数这类的如何操作?

**Comment by elcarim5efil** [comment]
1. 不建议调用小程序的 setData，尽量用 vue 的 api。如果实在要调用，可以用 this.$mp.page.setData
2. 直接把对象放到 Vue 的 data 上，使用 Vue 的绑定语法，`:animation="animationData"` 应该可以实现

**Comment by microyulive** [comment]
> 1. 不建议调用小程序的 setData，尽量用 vue 的 api。如果实在要调用，可以用 this.$mp.page.setData
> 2. 直接把对象放到 Vue 的 data 上，使用 Vue 的绑定语法，`:animation="animationData"` 应该可以实现

多谢！
