### ISSUE TITLE
请问如何添加单元测试(jest)

### ISSUE THREAD

**Issue by jerecui** [kaola-fed/megalo#260]
如题。
直接移植 vue 项目的单元测试配置一直出错，请问有没有示例代码？

**Comment by elcarim5efil** [comment]
报的什么错？单元测试是 js 还是包含了 vue 文件？

**Comment by jerecui** [comment]
> 报的什么错？单元测试是 js 还是包含了 vue 文件？

* 如果用 jest 直接跑比如：node '/xxxx/node_modules/.bin/jest' '/xxxx/tests/unit/api/order.spec.js' -t 'not expired'
会抛如下错误：
 Test suite failed to run

    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

      at Object.<anonymous> (node_modules/@megalo/babel-preset-app/index.js:3:44)
原因是这么跑没有加载环境变量MEGALO_CLI_CONTEXT
```node
const path = require('path')
const fs = require('fs')
const isUseTypescript = fs.existsSync(path.join(process.env.MEGALO_CLI_CONTEXT, 'tsconfig.json'))
```

* 而一般的 vue 项目是用的  vue-cli-service test:unit
如果添加了 vue-cli-service 来跑测试应该是可以跑过的，但 vue-cli-service似乎 与 megalo-cli-service 是冲突的，添加了前者项目就无法正常工作了。
而 megalo-cli-service 并没有 test:unit 的命令，目前webpack 还不熟悉，似乎改一下加个配置就好了。

**Comment by cythiaY** [comment]
老哥，你问题解决了吗

**Comment by cythiaY** [comment]
老哥，你问题解决了吗 没有test：unit命令 怎么操作

**Comment by jerecui** [comment]
> 老哥，你问题解决了吗 没有test：unit命令 怎么操作

还没呢

**Comment by jerecui** [comment]
yarn add @vue/cli-plugin-unit-jest @vue/cli-service babel-jest @vue/test-utils --dev

就可以了 之前少加了cli-service..
