### ISSUE TITLE
脚本引入ts文件编译停止

### ISSUE THREAD

**Issue by zhepama** [kaola-fed/megalo#261]
info.vue中
`
<script lang="ts" src="./info.ts"></script>
<style lang="stylus">
@import './info.styl';
</style>
`
然后编译的时候.到达57%就停止了

using @megalo/template-compiler@0.10.1
using megalo@0.10.1
configureWebpack执行了
Starting type checking service...
Using 2 workers with 2048MB memory limit
 57% building 70/71 modules 1 active ...info.vue?vue&type=template&id=e0fbc7ca&终止批处理操作吗(Y/N)? y

直接在vue文件中写人ts没有问题.

**Comment by elcarim5efil** [comment]
暂时不能通过外部引入的 ts 脚本的方式进行构建。
