### ISSUE TITLE
新版配置，ts +vuex  commit 递归死循环

### ISSUE THREAD

**Issue by webtianjia** [kaola-fed/megalo#264]
## 编辑器错误
![image](https://user-images.githubusercontent.com/22638382/58079979-d6eb1000-7be4-11e9-9b50-a90084fc1907.png)
## vuex
![image](https://user-images.githubusercontent.com/22638382/58079982-d94d6a00-7be4-11e9-9982-652802a339c6.png)

## 页面组件
![image](https://user-images.githubusercontent.com/22638382/58079989-db172d80-7be4-11e9-85f4-902e648f1818.png)
![image](https://user-images.githubusercontent.com/22638382/58079995-dce0f100-7be4-11e9-99f9-16bb59521ae4.png)

## 页面对象打印

![image](https://user-images.githubusercontent.com/22638382/58080330-9770f380-7be5-11e9-907c-a52f049ba216.png)
![image](https://user-images.githubusercontent.com/22638382/58080336-993ab700-7be5-11e9-93c3-4d8b52a4e8ca.png)

**Comment by elcarim5efil** [comment]
这个看着像业务逻辑的问题，可以尝试用 vuex 的 logger 调试一下数据流。

**Comment by webtianjia** [comment]
@elcarim5efil  感谢你的回答， 这个vuex 是我从第一版megalo cli 移植过来的

**Comment by webtianjia** [comment]
请 关闭这个是我的问题，在 mutations SetErrorData 少写了一个传递过来的参数~——~
