### ISSUE TITLE
建议新增对async/await的支持

### ISSUE THREAD

**Issue by unclexiao** [kaola-fed/megalo#27]
为避免过多的回调地狱，建议新增对async/await语法的支持，我的做法如下：

1. 引入**transform-runtime**包
```bash
npm i babel-plugin-transform-runtime 
```

2. 修改**babel**配置文件
```javascript
{
  "plugins": ["transform-runtime"],
  "presets": [ "env", "stage-0" ]
}

```

3. 修改**webpack**配置文件(createBaseConfig.js)
```javascript
     {
          test: /\.js$/,
          exclude: /(node_modules|bower_components)/,
          use: [
            {
              loader: 'babel-loader',
              options: {
                babelrc: true
              }
            }
          ]
    },
```

不知官方后期是否考虑列为新特性？

**Comment by elcarim5efil** [comment]
好建议，但这也不算是框架特性，但我们会补充到 demo 和 cli 里面的。

**Comment by elcarim5efil** [comment]
已更新

**Comment by centuryHarbour** [comment]
在sao/1.61的版本中使用async/await报错，
![image](https://user-images.githubusercontent.com/20835837/55319198-f26c5100-54a6-11e9-9104-b6c7900b1035.png)
![image](https://user-images.githubusercontent.com/20835837/55319241-087a1180-54a7-11e9-9548-5cf1735fa078.png)
希望作者能尽快解决

**Comment by bigmeow** [comment]
把小程序开发者工具自带的 es6转es5  勾选去掉
