### ISSUE TITLE
初始化项目构建报错

### ISSUE THREAD

**Issue by Dewyzee** [kaola-fed/megalo#270]
1.按照官网步骤全局安装``sao``
2.通过cli命令创建初始化项目
3.安装依赖后运行``npm run dev:wechat``报错
![image](https://user-images.githubusercontent.com/4916726/58688128-259f6380-83b6-11e9-97e0-08dc0b85e3b4.png)
操作系统：macOS Mojave
node版本：v10.15.0

**Comment by zhmlsj** [comment]
打开node_modules\@megalo\target\lib\plugins\MegaloPlugin.js 中搜索unshift 找到
 index != vueIndex && rules[index].use.unshift( loader )
改成
 index != vueIndex && rules[index].use && rules[index].use.unshift(loader)
再运行 npm run dev:wechat 就可以了

**Comment by syxchina** [comment]
同遇到，官方还是解决下吧

**Comment by fengzilong** [comment]
升级下 @megalo/target@0.7.3
