### ISSUE TITLE
单独js配置config引用第三方库报错

### ISSUE THREAD

**Issue by chinabf** [kaola-fed/megalo#280]
import App from '.'
import Vue from 'vue'

const app = new Vue(App)

app.$mount()

export default {
  config: {
    navigationBarTitleText: '测试',
    usingComponents: {
      'van-notice-bar': '/native/vant/notice-bar/index'
    }
  }
}

**Comment by chinabf** [comment]
VM676:1 WXMLRT_$gwx:./pages/index/index.wxml:import:1:1: Path `../../components/index$1e4431e9.wxml` not found from `./pages/index/index.wxml`.
console.warn @ VM676:1
t.(anonymous function) @ WAService.js:1
_wp @ appservice?t=1562293938615:17
_ai @ appservice?t=1562293938615:1013
m190 @ appservice?t=1562293938615:14000
(anonymous) @ appservice?t=1562293938615:14025
e @ WAService.js:1
a.create @ WAService.js:1
A.prepare @ WAService.js:1
A._advancedCreate @ WAService.js:1
A.create @ WAService.js:1
(anonymous) @ WAService.js:1
Fe @ WAService.js:1
value @ WAService.js:1
Tt @ WAService.js:1
(anonymous) @ WAService.js:1
It @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
i.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1562293938615:14037
n.registerCallback.t @ appservice?t=1562293938615:14037
u.forEach.t @ appservice?t=1562293938615:14037
(anonymous) @ appservice?t=1562293938615:14037
a.onmessage @ appservice?t=1562293938615:14037
VM676:1 WXMLRT_$gwx:./pages/index/index.wxml:template:2:14: Template `index$1e4431e9` not found.
console.warn @ VM676:1
t.(anonymous function) @ WAService.js:1
_wp @ appservice?t=1562293938615:17
_w @ appservice?t=1562293938615:1018
m190 @ appservice?t=1562293938615:14013
(anonymous) @ appservice?t=1562293938615:14025
e @ WAService.js:1
a.create @ WAService.js:1
A.prepare @ WAService.js:1
A._advancedCreate @ WAService.js:1
A.create @ WAService.js:1
(anonymous) @ WAService.js:1
Fe @ WAService.js:1
value @ WAService.js:1
Tt @ WAService.js:1
(anonymous) @ WAService.js:1
It @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
i.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1562293938615:14037
n.registerCallback.t @ appservice?t=1562293938615:14037
u.forEach.t @ appservice?t=1562293938615:14037
(anonymous) @ appservice?t=1562293938615:14037
a.onmessage @ appservice?t=1562293938615:14037
VM676:1 WXMLRT_$gwx:./pages/index/index.wxml:import:1:1: Path `../../components/index$1e4431e9.wxml` not found from `./pages/index/index.wxml`.
console.warn @ VM676:1
t.(anonymous function) @ WAService.js:1
_wp @ appservice?t=1562293938615:17
_ai @ appservice?t=1562293938615:1013
m190 @ appservice?t=1562293938615:14000
(anonymous) @ appservice?t=1562293938615:14025
e @ WAService.js:1
value @ WAService.js:1
value @ WAService.js:1
(anonymous) @ WAService.js:1
i.doUpdates @ WAService.js:1
A.setData @ WAService.js:1
(anonymous) @ WAService.js:1
doUpdate @ megalo.mp.esm.js:5169
instantUpdate @ megalo.mp.esm.js:5184
onLoad @ megalo.mp.esm.js:7219
(anonymous) @ WAService.js:1
p.__callPageLifeTime__ @ WAService.js:1
Tt @ WAService.js:1
(anonymous) @ WAService.js:1
It @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
i.emit @ WAService.js:1
emit @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
e @ appservice?t=1562293938615:14037
n.registerCallback.t @ appservice?t=1562293938615:14037
u.forEach.t @ appservice?t=1562293938615:14037
(anonymous) @ appservice?t=1562293938615:14037
a.onmessage @ appservice?t=1562293938615:14037
VM676:1 WXMLRT_$gwx:./pages/index/index.wxml:template:2:14: Template `index$1e4431e9` not found.

**Comment by chinabf** [comment]
`vue页面里面引用不会报错
<config>
    {
    "navigationBarTitleText": "测试",
    "usingComponents": {
    "van-notice-bar": "/native/vant/notice-bar/index"
    },
    }
</config>`

**Comment by chinabf** [comment]
vue页面里面引用不会报错，单独js配置会报错
<config>
    {
    "navigationBarTitleText": "测试",
    "usingComponents": {
    "van-notice-bar": "/native/vant/notice-bar/index"
    },
    }
</config>

**Comment by bigmeow** [comment]
因为main.js的这个config配置是被babel静态分析解析出来的，对于babel来说它就是一个字符串，它会去main.js里查找满足语法要求的这个字符串配置，你把它拿出去了，肯定就找不到这个配置了。
所谓静态分析，就是配置的这段代码不会在小程序的js环境里运行，而是被当成一个静态文件去解析里面的字符串

**Comment by chinabf** [comment]
好的谢谢大佬
