### ISSUE TITLE
扩展类型megalo类型文件，.vue文件依旧不能识别

### ISSUE THREAD

**Issue by sanriqing** [kaola-fed/megalo#285]

**Comment by bigmeow** [comment]
完全不知道你在说啥。。。
是指新建一个页面么 新建一个页面要用命令重启项目

**Comment by sanriqing** [comment]
> 完全不知道你在说啥。。。
> 是指新建一个页面么 新建一个页面要用命令重启项目

嗯。扩展megalo中扩展vue的定义，目前vscode识别不到，目前采用定义vue的方式绕开了
