### ISSUE TITLE
建议增加 ‘端能力 API’ 的自动处理

### ISSUE THREAD

**Issue by geminate** [kaola-fed/megalo#32]
3端小程序各自有各自的 Api 写法，如拍照、扫描二维码等等，**建议提供统一处理方式**
否则 均需要 手动 判断 platform，会形成大量无用代码且繁琐。

**可参考 Taro 的处理方式**
https://nervjs.github.io/taro/docs/native-api.html

其中路由跳转部分 我已经单独 抽出了一个插件，[megalo-router-patch](https://github.com/geminate/megalo-router-patch)，mpvue 也有类似插件，便于迁移 ，希望可以 加入到 本项目的 readme 或 demo 中。

**Comment by elcarim5efil** [comment]
很好的建议，关于这个我们有计划的，包括 UI，不过近期人力有限，等确定方案之后希望能和社区一起完善。

**Comment by elcarim5efil** [comment]
[megalo-api](https://github.com/megalojs/megalo-api)

仓库已开，不过正在建设中，很快会有第一次 commit

**Comment by geminate** [comment]
感谢，我们团队已经 写了一个插件临时处理该问题  [megalo-api-patch](https://github.com/MagicSpyTeam/megalo-api-patch)
由于工作量较大，大约只实现了 20% 左右的我们会用到的接口，使用的是 混入的方式。
考虑到运行效率等原因，非常期待官方的 api 处理插件。
