### ISSUE TITLE
运行严选的demo时微信开发者工具报错

### ISSUE THREAD

**Issue by zjtt** [kaola-fed/megalo#37]
![image](https://user-images.githubusercontent.com/22001904/48815472-9c113800-ed79-11e8-85bb-3948bb3a29fe.png)
![image](https://user-images.githubusercontent.com/22001904/48815509-adf2db00-ed79-11e8-92a5-cdd25bac3472.png)

**Comment by elcarim5efil** [comment]
这个应该是没有配置业务白名单域名吧

**Comment by huixisheng** [comment]
也出现第二章图报错  https://github.com/zwwill/megalo-yanxuan-demo/issues/1

**Comment by fengzilong** [comment]
@huixisheng 第二张图的报错就是前一个引起的吧

**Comment by huixisheng** [comment]
我没有第一张图报错，域名检测的选项关闭了。
我的报错如下: 
![image](https://user-images.githubusercontent.com/1518967/49328126-0e69ef80-f5a6-11e8-81e0-7e692149978c.png)
![image](https://user-images.githubusercontent.com/1518967/49328128-13c73a00-f5a6-11e8-9f34-50038086ffb9.png)

**Comment by Lixq1** [comment]
我也是这个问题，请问是什么原因

**Comment by elcarim5efil** [comment]
应该是获取不到异步接口的数据，然后变量获取失败吧。微信对请求接口有权限限制的。

[异常代码](https://github.com/zwwill/megalo-yanxuan-demo/search?q=.tlt&unscoped_q=.tlt)

**Comment by cyxhoo** [comment]
Block2.vue文件需要加上判断，<div class="tlt tlt-new" v-if="head">{{head.tlt}}</div>
