### ISSUE TITLE
建议 | 给出相应的开发工具【项目设置】标准

### ISSUE THREAD

**Issue by auven** [kaola-fed/megalo#38]
**如图，这里的配置是否有一个标准，如果我开启或关闭某些设置，是否对项目的运行会造成影响？**

![301542768690_ pic_hd](https://user-images.githubusercontent.com/23731087/48815984-6b320280-ed7b-11e8-8301-625cef96e806.jpg)

例如：我的项目中使用了 vant-weapp 的组件，需要开启 es6 转 es5 才能正常使用 vant-weapp 。

**Comment by zwwill** [comment]
后期会在文档中标注

**Comment by auven** [comment]
@zwwill  希望你们团队积极优化和完善，正在用本项目做一个上线项目，希望能少点坑，感谢大佬们！^v^

**Comment by zwwill** [comment]
@auven 感谢支持，因为人手不足，目前也很难顾及的比较全面，另外很多坑是我们在设计时没考虑到的，不过只要你们提出issue，肯定会处理的。

**Comment by Airkro** [comment]
正如你的举例 ，这是 vant-weapp 的问题，本质上和 megalo 无关。就算你不用 megalo ，只要用了 vant-weapp 这个问题也是存在的。megalo 有坑，但你说的这个这个不算。也不可能每个都去标注， UI组件库那么多。

**Comment by Airkro** [comment]
像 vant-weapp 这样的项目通常都是复制出来使用，并没有通过 megalo 的编译。至于megalo 编译的代码，需不需要开启 `es6 转 es5` 取决于开发者的webpack配置是什么样的。

**Comment by auven** [comment]
@Airkro  对呀，我这里是想阐述 `我使用 vant-weapp 开启 es6 转 es5` 后，是否会对 megalo 默认的 webpack 配置产生影响。所以想询问是否有相关的配置标准，如果 megalo 的构建工具编译后的代码不能开启 `es6 转 es5` ，而我要使用 `vant-weapp` 又必须开启，那时候该如何处理。

**Comment by Airkro** [comment]
`es6 转 es5` 开启是没问题的，因为最基本的层面，正常情况下babel转换过的代码就算再转一遍也不会出问题。没有用第三方组件库的话，可以不开启以达到加速效果。但是相应的将babel配置到测试环境所需的最低要求，否则会无法运行，所以对Babel不熟悉的建议始终开启。正式上线时也建议开启。
另外个人不建议开启 `代码保护` ，出错率还挺高的。
