### ISSUE TITLE
[BUG] 嵌套组件构建后路径丢失，提示找不到文件

### ISSUE THREAD

**Issue by auven** [kaola-fed/megalo#40]
![371542777888_ pic_hd](https://user-images.githubusercontent.com/23731087/48820721-2fa23300-ed91-11e8-9d5f-7d9c48b66d58.jpg)

![381542777914_ pic_hd](https://user-images.githubusercontent.com/23731087/48820733-36c94100-ed91-11e8-87ee-bb4506eff0e6.jpg)

![391542777939_ pic_hd](https://user-images.githubusercontent.com/23731087/48820742-3df04f00-ed91-11e8-8f84-8fb7929b9352.jpg)

![421542778033_ pic_hd](https://user-images.githubusercontent.com/23731087/48820753-46e12080-ed91-11e8-8f0b-8d1cbb28fca2.jpg)

**Comment by elcarim5efil** [comment]
![image](https://user-images.githubusercontent.com/8703947/48823174-ccb59980-ed9a-11e8-8910-ed199bc69865.png)
![image](https://user-images.githubusercontent.com/8703947/48823190-ddfea600-ed9a-11e8-80d8-cb042cce61cd.png)

本地没有复现这个问题，能看看你的目录结构吗？

**Comment by auven** [comment]
@elcarim5efil  我知道了，因为我的组件是用**横线**的方式写的。如下
``` vue
<template>
  <base-page class="app" page-title="首页">
    <hello-world color="#007d37"></hello-world>
    <a url="/pages/test/index">跳转test页面1</a>
  </base-page>
</template>
```
改成**驼峰**后就不会了
``` vue
<template>
  <BasePage class="app" page-title="首页">
    <HelloWorld color="#007d37"></HelloWorld>
    <a url="/pages/test/index">跳转test页面1</a>
  </BasePage>
</template>
```
**这里的话，我想问是否可以支持横线式的组件标签写法，如果不支持，希望能在文档里说明一下，以防大家踩坑。**

**Comment by elcarim5efil** [comment]
megalo@0.04
@megalo/template-compiler@0.4.0

修复，[changelog](http://megalojs.org/#/changelog/CHANGELOG?id=_040-20181121)
