### ISSUE TITLE
下载官网的cli，没有wap版本的打包配置，有计划加进来吗？

### ISSUE THREAD

**Issue by weijiatan456** [kaola-fed/megalo#42]
或者说有教程吗，咋整合？

**Comment by elcarim5efil** [comment]
在 UI 库和 API 库没有出来以前，其实还不建议完全得用一套代码生成小程序和 h5。在我们已有的一些实践中，很多情况下， h5 和小程序交互、业务逻辑是不太一样，也不能百分百共用。megalo 目前主要想做的是，让两端的开发体验尽量保持一致，提升迁移和维护时的效率。

但在后面，UI 库和 API 库出来以后，我们也会整理 h5 端的代码复用方案，也把 h5 端的构建方式加入到 cli 当中。

**Comment by wanganxp** [comment]
> 或者说有教程吗，咋整合？

uni-app有打包h5，也是基于vue的，可以去了解下

**Comment by weijiatan456** [comment]
> > 或者说有教程吗，咋整合？
> 
> uni-app有打包h5，也是基于vue的，可以去了解下

感谢，最近已经上手uni-app了

**Comment by wangzhengbo** [comment]
使用vant和vant-weapp结合vue-cli来打包h5
