### ISSUE TITLE
百度小程序在编译时报错

### ISSUE THREAD

**Issue by volantWizard** [kaola-fed/megalo#45]
![image](https://user-images.githubusercontent.com/21339697/48914636-0ed3fd80-eeb7-11e8-89bf-c33fcb5cc3e0.png)

-百度小程序编译后报错，应该时async/await的问题，但是我已经引入run-time支持。微信、支付宝平台下无报错。
- 版本信息如下
"@megalo/target": "^0.3.0",
"@megalo/template-compiler": "^0.2.2",
"megalo": "^0.4.0",

**Comment by elcarim5efil** [comment]
`@megalo/template-compiler` 请更新到与 `megalo` 对应的版本 `0.4.0`，因为 runtime 和编译出来的 render 方法与模版文件需要相对应，所以这两个包应该绑定版本。

**Comment by volantWizard** [comment]
已更新到"@megalo/target": "^0.4.0", 问题依然存在。好像没升级前都是可以编译的！

**Comment by elcarim5efil** [comment]
@megalo/taget 最新是 0.3.2
@megalo/template-compiler 最新是 0.4.0

我本地跑了，是没问题的。

**Comment by elcarim5efil** [comment]
先 close，如果有问题再 open 吧。

**Comment by volantWizard** [comment]
找到问题了，已经解决！transform-runtime，编译的问题。babelrc配置好后就ok了！
