### ISSUE TITLE
megalo-cli创建的项目在有多页面时编译错误

### ISSUE THREAD

**Issue by zhdwwf** [kaola-fed/megalo#46]
### 问题 
使用megalo/cli创建项目后直接编译成功，增加一个page后编译报如下错误：
![image](https://user-images.githubusercontent.com/564279/49060927-789f2f00-f24a-11e8-96a6-2d7827f8958a.png)

项目代码地址：https://github.com/zhdwwf/megalo-demo

 ### 版本：
1. win10
2. node 10.13.0
3. @megalo/target 0.3.1
4. @megalo/template-compiler 0.4.0

**Comment by zwwill** [comment]
vue 的 template 不可为空，以提PR  
https://github.com/zhdwwf/megalo-demo/pull/1
https://github.com/zhdwwf/megalo-demo/pull/2

**Comment by zhdwwf** [comment]
merge后问题已解决，感谢回复!
