### ISSUE TITLE
微信小程序Picker组件range参数无法响应其绑定对象的变化

### ISSUE THREAD

**Issue by francis-woo** [kaola-fed/megalo#47]
微信小程序 Picker组件，动态绑定的range对象无法响应对象的变化 ，点击addcity按钮，picker里的选项没有增加。

测试组件代码 

```
<template>
  <div>
    <picker
      class="_picker"
      mode="multiSelector"
      range-key="name"
      :value="mindex"
      :range="range"
    >testing</picker>

    <div @click="addCity">add City</div>
  </div>
</template>

<style>
._picker {
  padding: 13px;
  background-color: #ffffff;

  height: 100rpx;
  width: 200rpx;
  border: 1rpx solid red;
}
</style>

<script>
export default {
  methods: {
    addCity() {
      this.range[0].push({ id: 9, name: "云南" });
    }
  },
  data() {
    return {
      range: [
        [{ id: 0, name: "北京" }, { id: 1, name: "上海" }],
        [{ id: 2, name: "海淀区" }, { id: 3, name: "玄武区" }]
      ],
      mindex: [0, 0]
    };
  }
};
</script>
```

**Comment by luanwulin** [comment]
大兄弟，，这不是框架问题是 vue 的问题，你要用$set来触发数组的修改，，

**Comment by francis-woo** [comment]
@luanwulin 
> 大兄弟，，这不是框架问题是 vue 的问题，你要用$set来触发数组的修改，，

跟这个没关系吧，push方法是可以触发修改检测的

**Comment by zwwill** [comment]
@francis-woo  可以尝试传入String，或者增加filter操作等

**Comment by BoltDoggy** [comment]
@zwwill @luanwulin 今天我们组也遇到了这个问题. 通过一系列排查, 排除 megalo 的原因.

当然肯定也不是 vue 自身的问题, 虽然 新老 vnode 没变, 但是数组 push 确实可以触发视图更新.

```
<template>
  <div>
    <!-- 这里通过一行来进行验证 -->
    {{ range }}
    <picker
      class="_picker"
      mode="multiSelector"
      range-key="name"
      :value="mindex"
      :range="range"
    >testing</picker>

    <div @click="addCity">add City</div>
  </div>
</template>
```

结果会发现直接显示的  range 是更新了的, 但是 picker 没更新.

Picker 作为一个原生组件, range 传入多维数组的时候, 如果数组要变更内容, 必须指向一个新的数组地址.

数组内的变化不会响应 Picker 更新的, 但是小程序用 this.setData 来更新数据, 这种问题就不容易暴露出来.

Megalo 很优秀, Vue 那是自然都不用说.

感谢 Megalo 让我们能够以 Vue 的体验来使用微信小程序.

不知道 Picker 的这个问题, 适不适合在 Megalo 这一层做到抹平.

**Comment by zwwill** [comment]
@BoltDoggy 后期会由 megalo-ui 的组件抹平

**Comment by BoltDoggy** [comment]
@zwwill 抱歉了, 刚才的结论有点草率, 最新测试的

```
    this.data.range[1] = [20];
    this.setData({
      range: this.data.range
    });
```

小程序原生的 setData 变更数组内容会更新 range.

Megalo 中唯一调用 setData 的地方, 

```
export function createUpdateFn (page) {
  const buffer = new Buffer()

  function doUpdate () {
    const data = buffer.pop()

    if (!isEmptyObj(data) && page.setData) {
      console.log(data);
      page.setData(data)
    }
  }
```

如果不添加以下行

```
<!-- 这里通过一行来进行验证 -->
    {{ range }}
```

将不会触发 doUpdate().

**Comment by elcarim5efil** [comment]
先看看 vue web 端的代码：

https://github.com/vuejs/vue/blob/dev/src/platforms/web/runtime/modules/attrs.js#L41

在比较 attr 时，是直接比较两个变量的，不是 deepEqual，demo 里是在同一个数组上做操作，因此数组的引用是一样的，所以不会触发更新。web 端这样做原因应该考虑到有效的 attribute 设置只会是 string。

在小程序里面，attribute 其实是小程序原生组件的 property，所以可以是对象、数组变量，所以针对这种情况，要考虑针对性地进行优化。
