### ISSUE TITLE
props 的default 不能使用函数

### ISSUE THREAD

**Issue by ishareme** [kaola-fed/megalo#48]
props 的default 不能使用函数

写成 default: true 正常

![image](https://user-images.githubusercontent.com/25175055/49143195-7d8cdd00-f335-11e8-96ad-11058d16dd45.png)

![image](https://user-images.githubusercontent.com/25175055/49143475-0efc4f00-f336-11e8-9afa-4c5de6ec0ce7.png)

**Comment by zwwill** [comment]
检测一下引用，是否有命名不匹配问题

**Comment by ishareme** [comment]
closes #48

**Comment by elcarim5efil** [comment]
这个问题与 props 无关，应该和监听事件的 handler 未定义有关，将在下一个版本修复。
