### ISSUE TITLE
首页执行了详情页的代码，导致没有 $mp

### ISSUE THREAD

**Issue by ishareme** [kaola-fed/megalo#50]
进入小程序的时候 首页没去点击去详情页， 反而执行了 详情页的代码， 

执行顺序为： app.vue created ==> detail.vue created ==> index.vue created

首页的created反而更晚执行

![image](https://user-images.githubusercontent.com/25175055/49210909-3831e380-f3f9-11e8-949e-d0afcd06068b.png)

**Comment by zwwill** [comment]
megalo 主包升级到 0.4.0 即可
相关 npm 可以一同更新
```
{
  "@megalo/target": "^0.4.0",
  "@megalo/template-compiler": "^0.4.0",
  "megalo": "^0.4.0"
}
```

**Comment by ishareme** [comment]
还是存在

**Comment by zwwill** [comment]
问题已解决
