### ISSUE TITLE
父组件不传 有定义name的 slot 的内容时报错

### ISSUE THREAD

**Issue by ishareme** [kaola-fed/megalo#53]
父组件不传 有定义name的 slot 的内容时报错

![image](https://user-images.githubusercontent.com/25175055/49327479-605a4780-f59d-11e8-989f-8b0135102b4f.png)

![image](https://user-images.githubusercontent.com/25175055/49327480-65b79200-f59d-11e8-9c1c-06f7375aacf7.png)

![image](https://user-images.githubusercontent.com/25175055/49327484-694b1900-f59d-11e8-935c-2b7f8fdbef01.png)

**Comment by elcarim5efil** [comment]
`megalo@0.5.1 @megalo/template-compiler`
修复
