### ISSUE TITLE
支持头条小程序

### ISSUE THREAD

**Issue by elcarim5efil** [kaola-fed/megalo#55]
https://developer.toutiao.com/homepage

**Comment by 422656004** [comment]
请问如何配置才能支持头条小程序呢

**Comment by elcarim5efil** [comment]
@422656004 还未支持，如果支持，和其他平台使用方式应该会保持一致。

**Comment by 422656004** [comment]
我尝试修改了build 源码，就模仿wechat来写的。目前还没有编译通过~~~~

**Comment by elcarim5efil** [comment]
昨天才提交开发者申请，现在还没审核通过。😂。简单看了一下文档，和微信的差不多，把 preset 里面的指令和 target 的输出文件后缀改一下应该差不多了。

**Comment by 422656004** [comment]
太好了，那我就不折腾了，坐等通过，下载更新，大神v5

**Comment by elcarim5efil** [comment]
权限申请不下来...

**Comment by ac51300696** [comment]
老哥加油，不行又得fork下来并行搞了

**Comment by ac51300696** [comment]
有没有fork的项目地址

**Comment by ac51300696** [comment]
> 权限申请不下来...

老哥有fork的分支不
