### ISSUE TITLE
如何手动切换页面呢?

### ISSUE THREAD

**Issue by 422656004** [kaola-fed/megalo#58]

**Comment by bigmeow** [comment]
1.在项目```megalo-demo/src/index.js```里，找到```pages```选项，将要切换的首屏页面放到pages数组的第一个
2.在小程序开发者工具里，打开Console控制台,使用代码```wx.navigateTo(配置)```切换

**Comment by MadokamiO** [comment]
推荐 [megalo-router-patch](https://github.com/geminate/megalo-router-patch)
拍扁了 多端小程序的 路由跳转
