### ISSUE TITLE
在组件上写class 不会继承 父组件的scoped

### ISSUE THREAD

**Issue by ishareme** [kaola-fed/megalo#61]
在组件上写class 不会继承 父组件的scoped

![image](https://user-images.githubusercontent.com/25175055/49498638-af0e2700-f8a6-11e8-972d-75fc2f681538.png)

**Comment by fengzilong** [comment]
我的理解是 `upload-btn` 上面少了 `v-92dff1bc`？

方便贴下源码以及预期结果么？

**Comment by ishareme** [comment]
@elcarim5efil 他比较了解 之前有跟他在对接

**Comment by elcarim5efil** [comment]
父组件调用子组件时，需要将父组件 scoped id 传递给子组件，现在考虑在模版中通过 data 将 scoped 逐级往下传递

**Comment by elcarim5efil** [comment]
`megalo@0.7.0`，`@megalo/template-compiler@0.7.0` 支持了，可以试试。[changelog](http://megalojs.org/#/changelog/CHANGELOG?id=_070-20190101)。
