### ISSUE TITLE
项目自带的demo 在真机预览打开白屏

### ISSUE THREAD

**Issue by yangdaolong** [kaola-fed/megalo#62]
项目下载下来后，自带的demo，在支付宝开发工具里打开是正常的，但是用真机预览是白屏，

![image](https://user-images.githubusercontent.com/32027714/49556414-9bae9a80-f93e-11e8-88f1-bc65b63234b2.png)

**Comment by zwwill** [comment]
定位中。。

**Comment by zwwill** [comment]
你指的项目自带的demo 是这个吗？ 
https://github.com/kaola-fed/megalo-demo

**Comment by yangdaolong** [comment]
不是这个， 

是这个自带的就一个页面hello
创建 Megalo 工程
megalo my-megalo-pro
运行 npm run dev:alipay

然后用支付宝开发工具打开dist-alipay，点击预览在真机上扫码打开白屏

**Comment by zwwill** [comment]
cli 构建的吗？ 请问你用的cli哪个版本？

**Comment by yangdaolong** [comment]
@megalo/cli@0.3.0

**Comment by fxy060608** [comment]
@zwwill 我这里排查到是因为 Vue 源码src/core/util/next-tick.js中访问setImmediate导致的支付宝小程序真机报错，将setImmediate相关代码移除即可解决
`if (typeof setImmediate !== 'undefined' && isNative(setImmediate)) {
  macroTimerFunc = () => {
    setImmediate(flushCallbacks)
  }
} else`

**Comment by elcarim5efil** [comment]
@bigmeow setImmediate 去掉好像也同样报这个错

**Comment by n0rv1n** [comment]
我也遇到这个问题

**Comment by elcarim5efil** [comment]
最新版的 sdk 貌似修复了，没有复现，android 和 iOS 都正常。先关闭了。

**Comment by xiexieni1992** [comment]
[WORKER] onerror ["c.createElement is not a function. (In 'c.createElement(\"script\")', 'c.createElement' is undefined)","https://2018071660710198.hybrid.alipay-eco.com/index.worker.js",1,341522,{"line":1,"column":341522,"sourceURL":"https://2018071660710198.hybrid.alipay-eco.com/index.worker.js"}]megalo0.9版本还是有这个问题

**Comment by elcarim5efil** [comment]
支付宝 ide 更新到最新了吗？
