### ISSUE TITLE
新建项目的时候，author字段如果输入非法字符（\），会导致脚本报错。

### ISSUE THREAD

**Issue by lovelyyl** [kaola-fed/megalo#63]

**Comment by zwwill** [comment]
可以提供下截图。
另外，构建类的issue可以提到这里 https://github.com/megalojs/megalo-cli/issues

**Comment by lovelyyl** [comment]
![default](https://user-images.githubusercontent.com/45654799/49621400-1ee3f500-fa00-11e8-9dec-c913df16f1dd.png)


1、项目新建成功，命令行没有自动退出，ctrl+c都退不了。
2、上面那个图的情况，出了问题，ctrl+c结束不了程序。
