### ISSUE TITLE
v-show 无效

### ISSUE THREAD

**Issue by ishareme** [kaola-fed/megalo#64]
![image](https://user-images.githubusercontent.com/25175055/49581107-d38fff00-f98b-11e8-830d-2aa31dc7b86f.png)

![image](https://user-images.githubusercontent.com/25175055/49581116-dab70d00-f98b-11e8-99ce-977dfb22f7a8.png)

v-show 在 组件和非组件上都无效

megalo 0.5.3

**Comment by bigmeow** [comment]
没有重现，请编写一个剥离业务的最小化的demo。
另外建议查看一下编译后的文件，检查package.json和megalo相关的依赖（例如target），是否都升级到了最新版，并非只升级一个megalo就行
@ishareme

**Comment by elcarim5efil** [comment]
在组件上暂时是不支持的，非组件应该可以 ok 的。如果没有可复现代码，暂时先把 issue 关闭了。

**Comment by wiexin** [comment]
@elcarim5efil  碰到同样问题 v-show 改成v-if就可以 。排查发现v-show的元素如果display是flex，v-show会失效

**Comment by elcarim5efil** [comment]
嗯，v-show 是用 hidden 实现的，http://www.wxapp-union.com/article-2073-1.html，hidden 存在问题，在考虑是否需要换一种实现方式。
