### ISSUE TITLE
megalo@0.5.3 深层改变数据后 视图没更新

### ISSUE THREAD

**Issue by ishareme** [kaola-fed/megalo#65]
![image](https://user-images.githubusercontent.com/25175055/49581170-0afeab80-f98c-11e8-811d-aeda471b3f21.png)

0.5.3版本 这样子处理视图没有更新，  0.5.1版本是可以的

**Comment by bigmeow** [comment]
@ishareme 这也是一个正常的表现，请[点击这里](https://cn.vuejs.org/v2/guide/list.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)查看vue文档:

> 由于 JavaScript 的限制，Vue 不能检测以下变动的数组：
当你利用索引直接设置一个项时，例如：vm.items[indexOfItem] = newValue
当你修改数组的长度时，例如：vm.items.length = newLength

**Comment by ishareme** [comment]
@bigmeow 不是哦~~  这是在对象上新增数据，  但是 有调用 Object.assigin({}, xxxx)   应该是会检测到

**Comment by bigmeow** [comment]
![image](https://user-images.githubusercontent.com/10484248/49586124-3b9a1180-f99b-11e8-9f3c-3e93e3c20583.png)
这里改的索引是无效的，所以this.mDetail对象的属性值从来没有变过

**Comment by ishareme** [comment]
@bigmeow  this.mDetail.media.tags 他只是没有响应吧， 不代表数据没有改变过呀 ~~  最终我要变动的整体的mDetail ~~

**Comment by zwwill** [comment]
在触发 attr 的update时，vue传来的新老 vnode 为相同的值，个人认为是vue 的一个bug，类似于问题47 #47  可以通过转换数据类型解决

**Comment by ishareme** [comment]
@zwwill 我这边一切换到megalo 0.5.1 就ok 一切换到0.5.3就不行

**Comment by elcarim5efil** [comment]
0.5.1 版本由于框架获取 vmId 的逻辑触发了 render，0.5.3 进行了修复，你试试把这段段代码放到原生 vue 里面，应该也不会响应到视图吧。

**Comment by bigmeow** [comment]
如果非要强制渲染，试试`$forceUpdate()`?    当然最好尽量避免用这个 
https://cn.vuejs.org/v2/api/#vm-forceUpdate
