### ISSUE TITLE
监听不到scroll-x

### ISSUE THREAD

**Issue by ishareme** [kaola-fed/megalo#66]
![image](https://user-images.githubusercontent.com/25175055/49581287-6af55200-f98c-11e8-8c9d-ed1c837ec8e2.png)

![image](https://user-images.githubusercontent.com/25175055/49581353-96783c80-f98c-11e8-903e-851d15a90cea.png)

![image](https://user-images.githubusercontent.com/25175055/49581294-6fba0600-f98c-11e8-9398-75c2c1e55a4f.png)

![image](https://user-images.githubusercontent.com/25175055/49581403-d8a17e00-f98c-11e8-9439-54371e20bbac.png)

**Comment by bigmeow** [comment]
抱歉。。。没看明白。。。
请脱离业务，实现一个最小化页面demo

**Comment by elcarim5efil** [comment]
如果没有可复现代码，暂时先把问题关闭了。
