### ISSUE TITLE
push的时候监听到新值和旧值是一样的   都是新的值

### ISSUE THREAD

**Issue by ishareme** [kaola-fed/megalo#67]
![image](https://user-images.githubusercontent.com/25175055/49583485-549ec480-f993-11e8-92e0-6437b6735fe3.png)

![image](https://user-images.githubusercontent.com/25175055/49583472-4cdf2000-f993-11e8-8f60-6862a5596e70.png)

push的时候  新值和旧值是一样的   都是新的值

**Comment by bigmeow** [comment]
@ishareme  请查看下[vue的文档](https://cn.vuejs.org/v2/api/#vm-watch)，这是正常的表现：

> 注意：在变异 (不是替换) 对象或数组时，旧值将与新值相同，因为它们的引用指向同一个对象/数组。Vue 不会保留变异之前值的副本。

**Comment by ishareme** [comment]
close #67
