### ISSUE TITLE
有官方使用文档吗？

### ISSUE THREAD

**Issue by lczc** [kaola-fed/megalo#7]
官方使用文档有吗

**Comment by DestinyHunter** [comment]
同问

**Comment by FxPixels** [comment]
希望文档能带上，怎么使用第三方UI组件，合并到工程范例上

**Comment by F-loat** [comment]
和 mpvue 基本一致应该，区别和增强[文章](https://juejin.im/post/5bd2b014e51d457a7a0396ea)有写

**Comment by elcarim5efil** [comment]
文档正在准备中，我们也会逐步完善各种场景的使用方法。基本的工程配置可以参考 [示例代码](https://github.com/kaola-fed/megalo-demo) 和 [工程示例](https://github.com/kaola-fed/megalo-examples)

**Comment by elcarim5efil** [comment]
[文档](https://kaola-fed.github.io/megalo-docs/#/) 已经更新，内容我们在完善中，感觉反馈。
