### ISSUE TITLE
url-loader 转换后的静态图片真机不显示

### ISSUE THREAD

**Issue by wiexin** [kaola-fed/megalo#78]
`@megalo/target` 版本：0.6
`@megalo/template-compiler` 版本：0.6
`"@megalo/target` 版本0.5

操作系统 ：ios12

页面中引用本地静态图片资源， @megalo/template-compiler 编译后的路径在真机下不能显示
 
megalo-demo中的img页面引用静态图片 下所示：
![image](https://user-images.githubusercontent.com/18095039/49811320-fc563100-fd9d-11e8-936e-ef8ecc60b431.png)

**Comment by elcarim5efil** [comment]
url-loader 配置有问题，把

`name: '[path]/[name].[ext]'`

改成

`name: '[path][name].[ext]'`，就 ok 了。

谢谢反馈。
