### ISSUE TITLE
能用vue-cli3创建项目么？

### ISSUE THREAD

**Issue by qq157788394** [kaola-fed/megalo#8]
希望能有官方文档

**Comment by elcarim5efil** [comment]
文档在逐步完善，站点正在准备中。我们还没有针对 vue-cli 创建模版，目前应该还不支持。

**Comment by elcarim5efil** [comment]
[文档](https://kaola-fed.github.io/megalo-docs/#/) 已经更新，内容我们在完善中。

**Comment by elcarim5efil** [comment]
#10
