### ISSUE TITLE
mpvue和megal

### ISSUE THREAD

**Issue by lukaijin** [kaola-fed/megalo#82]
建议作者直接和mpvue作者合作吧，这东西没必要在造轮子，加大vue社区嘛

**Comment by zwwill** [comment]
mpvue 和 megalo 虽然使用上差别不大，都是基于vue 的，但框架设计上还是有很大区别的，mpvue 自身的设计也存在一些难以绕过的性能缺陷。所以另起炉灶反倒节省了成本。
另外从法务和技术依赖方面，公司大大们并不希望我们太过于依赖与别人。
至于megalo 的开源决策，是为了扩充vue社区，而不是扰乱。选择权全在用户自己。
