### ISSUE TITLE
创建项目时   一直卡在这里   found 0 vulnerabilities

### ISSUE THREAD

**Issue by VICTORYGS** [kaola-fed/megalo#85]
这是什么情况啊 一直卡在这里
![image](https://user-images.githubusercontent.com/33747619/50039692-2430e780-0071-11e9-8787-914d80e6ca26.png)

**Comment by elcarim5efil** [comment]
windows 吗？删除 node_modules，重新安装一下看看？

**Comment by VICTORYGS** [comment]
![image](https://user-images.githubusercontent.com/33747619/50129002-3f3e6a00-02b2-11e9-9c89-8f84a2074610.png)
还是会卡呢   不过 好像不影响 使用....

**Comment by elcarim5efil** [comment]
可能和 npm 有关，我先关闭 issue 了，如果有其他问题再看吧。
