### ISSUE TITLE
项目自带demo 里面 运行百度智能小程序 第一个链接点击无法跳转。tabBar里面可以

### ISSUE THREAD

**Issue by 422656004** [kaola-fed/megalo#86]
list: [
        {
          link: '/pages/todomvc/index',
          text: 'TodoMVC'
        },
        {
          link: '/pages/v-html/index',
          text: 'v-html'
        },
        {
          link: '/pages/v-model/index',
          text: 'v-model'
        },
        {
          link: '/pages/vuex/index',
          text: 'vuex'
        },
        {
          link: '/pages/webview/index',
          text: 'web-view'
        },
        {
          link: '/pages/native/index',
          text: '原生自定义组件'
        },
        {
          link: '/packageA/pages/a/index',
          text: 'packageA-a'
        },
        {
          link: '/packageA/pages/todomvc/index',
          text: 'packageA-todomvc'
        }
      ]

**Comment by bigmeow** [comment]
第一个链接的页面是tab页面，所以navigateTo跳转不过去的，用switchtab方法才能跳转，你忽略即可
