### ISSUE TITLE
在样式中直接使用标签不生效

### ISSUE THREAD

**Issue by zafkielkurumi** [kaola-fed/megalo#87]
.login {
    font-size: 14px;
    padding: 20px;
    &-img {
      text-align: center;
      margin-bottom: 10px;
      img {
        width: 60%;
      }
    }

  &-button {
      text-align: center;
      margin-top: 15px;
      span {
        width: 80%;
      }
    }
}

**Comment by zafkielkurumi** [comment]
好吧，写成 ._img  ._span这种生效，不能直接使用标签有时候还是有点麻烦

**Comment by elcarim5efil** [comment]
后面版本的计划中，将在构建时候做处理，将标签选择器转换为类选择器。
