### ISSUE TITLE
自定用了一个 loading 组件 ，引用 this.$loading.show('loading'); 报Cannot read property 'createElement' of undefined，如何才能正确使用呢？

### ISSUE THREAD

**Issue by 422656004** [kaola-fed/megalo#88]
import Vue from 'vue'
import Loading from './Loading'
import preventPageScroll from './utils/prevent-page-scroll'
/* 构建 instance */
let instance;
/* 构建构造函数 */
let LoadingConstructor = Vue.extend(Loading);
/* 初始化 instance */
let initInstance = () => {
  instance = new LoadingConstructor({
    el: document.createElement('div')
  });
  document.body.appendChild(instance.$el);
}
/* 是否正在显示 */
let isShowing = false;
/* 显示 loading */
let show = (text) => {
  if (!isShowing) {
    isShowing = true;
    /* 创建 instance */
    initInstance();
    /* 显示 */
    instance.show = true;
    instance.text = text ? text : '正在加载';
    /* 阻止页面滚动 */
    preventPageScroll.prevent();
  }
}
/* 隐藏 */
let hide = () => {
  instance.show = false;
  isShowing = false;
  /* 恢复页面滚动 */
  preventPageScroll.recover();
}
export default {
  install(Vue) {
    Vue.prototype.$loading = {
      show,
      hide
    }
  }
}

**Comment by zlxbuzz** [comment]
@422656004 小程序没有`document`这些操作。

**Comment by elcarim5efil** [comment]
小程序内无法操作 dom，需要更换实现方式
