### ISSUE TITLE
slot嵌套动态内容无效

### ISSUE THREAD

**Issue by owlikesj** [kaola-fed/megalo#92]
以 `<slot>{{ text }}</slot>` 方式定义组件 `TestSlot.vue`，然后以 `<test-slot :text="foo" />` 方式使用无效。

具体情况如下：

首先定义一个`TestSlot.vue`组件：
```vue
<template>
  <div class="test-slot">
    <slot>{{ text }}</slot>
  </div>
</template>

<script>
export default {
  name: "test-slot",
  props: {
    text: String
  }
};
</script>
```

然后在 根组件 中引入使用：
```vue
<template>
  <div class="test">
    <test-slot text="Test Slot1"></test-slot>
    <test-slot>Test Slot2</test-slot>
  </div>
</template>
```
在开发者工具中查看结果：
![testslot](https://user-images.githubusercontent.com/12454892/50136310-5e4cf400-02d2-11e9-9046-37aaaece00c5.jpg)

如图，在编译后的componet文件中引用变量h[3].t，而AppData里的变量是s[3].t，两者没有对应上

megelo版本："version": "0.6.2"

**Comment by elcarim5efil** [comment]
请问 compiler 和 target 的版本是多少？请把 compiler 更新到和 megalo 对应的版本试试？
@megalo/template-compiler@0.6.2
@megalo/target@0.5.0

**Comment by owlikesj** [comment]
> 请问 compiler 和 target 的版本是多少？请把 compiler 更新到和 megalo 对应的版本试试？
> @megalo/template-compiler@0.6.2
> @megalo/target@0.5.0

之前是
"@megalo/target": "^0.4.10",
"@megalo/template-compiler": "^0.5.2",

然后按你说的升级之后ok了，非常感谢~~
