### ISSUE TITLE
在页面中引入megalo-router，保持跟vue-router一致的开发体验

### ISSUE THREAD

**Issue by NextBoy** [kaola-fed/megalo#93]
# [megalo-router](https://github.com/NextBoy/megalo-router)
配合网易小程序框架megalo使用的router,尽量保持与vue-router一致的开发体验，减少技术成本，方便项目从web迁移到小程序

微信小程序、百度小程序、支付宝小程序通用语法，无需做适配

优化megalo的分包页面的跳转写法

megalo默认的分包页面之间的跳转比较麻烦，需要写相对路径，例如
例如从 home/index 跳转的到 packgeA/pages/a/index，相对路径为 ../../packgeA/pages/a/index。

使用megaloRouter则没有这种烦恼，直接
```js
    $router.push('/packgeA/pages/a/index')
```

欢迎大家使用和提意见
https://github.com/NextBoy/megalo-router

**Comment by b2nil** [comment]
> megalo默认的分包页面之间的跳转比较麻烦，需要写相对路径，例如
例如从 home/index 跳转的到 packgeA/pages/a/index，相对路径为 ../../packgeA/pages/a/index。

@NextBoy 好像并不存在这个问题， 我用下面的方式也可以直接从主页跳转到任何分包页面。
```javascript
toA() {
     this.$api.navigateTo('/packageA/pages/test')
},
toB() {
     this.$api.navigateTo('/pages/packageB/pages/test')
},
```

**Comment by NextBoy** [comment]
@b2nil 这个就得问官方啦。megalo官方文档是这么写的，话说$api是什么，megalo内置封装的么？

**Comment by NextBoy** [comment]
@b2nil 我自己试了下，的确并未有这种问题，但是megalo官方文档的确又是这么说的，不过这个主要是抹平语法差异哈

**Comment by NextBoy** [comment]
@b2nil  https://megalojs.org/#/senarios/subpackage

**Comment by b2nil** [comment]
@NexyBoy 
^_^文档确实有误导性。

确实，h5 同构需要抹平语法差异。能实现导航守卫就更好了。

**Comment by MadokamiO** [comment]
之前貌似看到过类似的插件啊。。。好像重复了啊
[megalo-router-patch](https://github.com/geminate/megalo-router-patch)
建议出一个官方版本吧，别再重复造轮子了，而且两个插件都没有实现 导航守卫功能

**Comment by NextBoy** [comment]
@AK57777 一个是直接用mpvue-router-patch直接改代码的，而且两者在用法上实际并不一样，我这个语法个vue-router是完全一致的

**Comment by elcarim5efil** [comment]
其实可以考虑整合成一个，一起维护。
