### ISSUE TITLE
url-loader转换后的图片，模拟器可以，真机不行

### ISSUE THREAD

**Issue by luanwulin** [kaola-fed/megalo#96]
img使用了widthFix模式，小程序自动设置高度。在模拟器上可以成功
![image](https://user-images.githubusercontent.com/16553854/50268514-0e9f3180-0466-11e9-8950-af0739c22721.png)
到了真机上就不行了
![image](https://user-images.githubusercontent.com/16553854/50268529-1959c680-0466-11e9-89c0-39590b958349.png)
是不是因为widthFix是小程序动态计算，url-loader转换出来地址也是动态的，两个时间上有先后

**Comment by elcarim5efil** [comment]
本地测试没有复现，安卓和 ios 上都试过。

```html
    <scroll-view scroll-y style="height: 200px;">
      <img mode="widthFix" class="pic" src="../../static/megalobox.jpg">
      <img mode="widthFix" class="pic" src="../../static/megalobox.jpg">
      <img mode="widthFix" class="pic" src="../../static/megalobox.jpg">
    </scroll-view>
```

**Comment by luanwulin** [comment]
@elcarim5efil 找到问题了，，原来是用了```image-webpack-loader``` 模拟器上就能打开压缩过的图片，真机不行了。多谢回复
