### ISSUE TITLE
微信小程序Input组件绑定input事件不能return返回值

### ISSUE THREAD

**Issue by wiexin** [kaola-fed/megalo#99]
"@megalo/target": "^0.5.2",
 "megalo": "^0.6",

`<input bindinput="inputFn"></input>`

inputFn: function(e){
    return e.detail.value.toUpperCase()
}
此时 input显示的值就是return返回的值

`<input @input="inputFn"></input>` 
同样的处理逻辑 打包后并不能return 返回值
打包后的函数如图所示：
![image](https://user-images.githubusercontent.com/18095039/50318823-8d47ad80-04fe-11e9-826c-2134f9208936.png)

**Comment by elcarim5efil** [comment]
`bindinput` 是小程序语法，应该用 vue 的绑定事件方式。vue 的事件监听 return 一个值没有意义吧？

**Comment by wiexin** [comment]
@elcarim5efil  原生写法中 可以在bindinput中return一个值来达到自定义显示，如自动转大小写
